# Generación de Ground Truth con DeepDoctection

Este notebook extrae tablas de los PDFs usando **deepdoctection** y genera un archivo JSON con el mismo formato del ground truth manual (`ground_truth_kge.json`).

El resultado está pensado para ser revisado y ajustado manualmente según las instrucciones en `ground_truth_manual.md`.

**Formato de salida:**
```json
{
  "documents": [
    {
      "paper_title": "...",
      "num_tables": N,
      "tables": [
        {
          "table_id": "table_1",
          "page": X,
          "evaluation": { "expected_rows": N, "expected_cols": M, "columns": [...] },
          "rows": [...]
        }
      ]
    }
  ]
}
```

In [41]:
import warnings
warnings.filterwarnings('ignore')

import json
from pathlib import Path
from bs4 import BeautifulSoup
import deepdoctection as dd

## Configuration

In [42]:
# Directorio con los PDFs y ruta de salida
PDF_DIR = Path("pdfs_prueba")
OUTPUT_PATH = Path("pdfs_prueba/ground_truth/ground_truth_deepdoctection.json")

# Los 5 papers a procesar
PDF_FILES = sorted(PDF_DIR.glob("*.pdf"))
print(f"PDFs encontrados: {len(PDF_FILES)}")
for p in PDF_FILES:
    print(f"  - {p.name}")

PDFs encontrados: 5
  - Adaptive Margin Ranking Loss for Knowledge Graph Embeddings via a Correntropy Objective Function.pdf
  - Adversarial Contrastive Estimation.pdf
  - Binarized Knowledge Graph Embeddings.pdf
  - HyperKG- Hyperbolic Knowledge Graph Embeddings for Knowledge Base Completion.pdf
  - Seq2RDF- An end-to-end application for deriving Triples from Natural Language Text.pdf

## Funciones auxiliares

In [43]:
def coerce_value(s: str):
    """Convierte un string a número si es posible. Valores vacíos/faltantes → '-'."""
    s = s.strip()
    if not s or s in ('–', 'N/A', 'n/a', 'nan'):
        return '-'
    if s == '-':
        return '-'
    s_clean = s.replace(',', '.')
    try:
        val = float(s_clean)
        # Devolver entero si no tiene parte decimal significativa
        return int(val) if val == int(val) else val
    except ValueError:
        return s


def build_grid(rows_elements):
    """
    Construye una cuadrícula 2D resolviendo rowspan/colspan.
    Devuelve: grid dict {(row, col): text}, max_row, max_col, max_header_reach
    """
    grid = {}
    max_header_reach = 1  # máximo alcance de spans en filas de datos

    for row_idx, row in enumerate(rows_elements):
        col_idx = 0
        for cell in row.find_all(['td', 'th']):
            # Saltar celdas ya ocupadas por un span previo
            while (row_idx, col_idx) in grid:
                col_idx += 1

            content = cell.get_text(separator=' ', strip=True)
            rowspan = int(cell.get('rowspan', 1))
            colspan = int(cell.get('colspan', 1))

            if rowspan > 1 or colspan > 1:
                max_header_reach = max(max_header_reach, row_idx + rowspan)

            for dr in range(rowspan):
                for dc in range(colspan):
                    grid[(row_idx + dr, col_idx + dc)] = content

            col_idx += colspan

    if not grid:
        return {}, 0, 0, 1

    max_row = max(r for r, _ in grid.keys()) + 1
    max_col = max(c for _, c in grid.keys()) + 1
    return grid, max_row, max_col, max_header_reach


def flatten_headers(grid, header_row_count: int, max_col: int):
    """
    Aplana cabeceras multinivel combinando con '_'.
    Elimina valores repetidos consecutivos (causados por rowspan propagation).
    Ejemplo: ['Models', 'WN18_MRR', 'WN18_Hits@_1', 'WN18_Hits@_3', ...]
    """
    columns = []
    for col_idx in range(max_col):
        parts = []
        prev = None
        for row_idx in range(header_row_count):
            val = grid.get((row_idx, col_idx), '').strip()
            if val and val != prev:
                parts.append(val)
            prev = val
        columns.append('_'.join(parts) if parts else '')
    return columns


def parse_table_html(html_str: str):
    """
    Parsea el HTML de una tabla extraída por deepdoctection.

    - Resuelve rowspan/colspan para detectar cuántas filas son cabecera.
    - Aplana encabezados multinivel (convención Dataset_Metrica_Variante).
    - Convierte valores numéricos a int/float; '-' para faltantes.

    Devuelve: (columns: list, data_rows: list[list]) o (None, None) si falla.
    """
    if not html_str:
        return None, None

    soup = BeautifulSoup(html_str, 'html.parser')
    table = soup.find('table')
    if not table:
        return None, None

    rows_elements = table.find_all('tr')
    if not rows_elements:
        return None, None

    grid, max_row, max_col, max_header_reach = build_grid(rows_elements)

    if not grid or max_col == 0 or max_row == 0:
        return None, None

    # Las filas de cabecera son las que forman el bloque de spans iniciales.
    # Debe quedar al menos 1 fila de datos.
    header_row_count = max(1, max_header_reach)
    header_row_count = min(header_row_count, max_row - 1)

    columns = flatten_headers(grid, header_row_count, max_col)

    # Extraer filas de datos
    data_rows = []
    for row_idx in range(header_row_count, max_row):
        row = [coerce_value(grid.get((row_idx, c), '')) for c in range(max_col)]
        # Ignorar filas completamente vacías o de guiones
        if all(v in ('-', '') for v in row):
            continue
        data_rows.append(row)

    return columns, data_rows


print("Funciones auxiliares cargadas.")

Funciones auxiliares cargadas.

## PDF text extraction (PDF Miner)

In [44]:
analyzer = dd.get_dd_analyzer(config_overwrite=[
    'USE_PDF_MINER=True',
    'USE_OCR=False',
    'OCR.USE_DOCTR=False',
])
print("Analyzer listo:", type(analyzer).__name__)

[0407 13:00.14 @dd.py:119]  INF  Config:
 {'CELL': {'FILTER': None,
          'PAD': {'BOTTOM': 60, 'LEFT': 60, 'RIGHT': 60, 'TOP': 60},
          'PADDING': False,
          'WEIGHTS': 'cell/d2_model_1849999_cell_inf_only.pt',
          'WEIGHTS_TS': 'cell/d2_model_1849999_cell_inf_only.ts'},
 'DEVICE': device(type='mps'),
 'ENFORCE_WEIGHTS': {'CELL': True, 'ITEM': True, 'LAYOUT': True},
 'ITEM': {'FILTER': ['table'],
          'PAD': {'BOTTOM': 60, 'LEFT': 60, 'RIGHT': 60, 'TOP': 60},
          'PADDING': False,
          'WEIGHTS': 'deepdoctection/tatr_tab_struct_v2/model.safetensors',
          'WEIGHTS_TS': 'item/d2_model_1639999_item_inf_only.ts'},
 'LANGUAGE': None,
 'LAYOUT': {'FILTER': None,
            'PAD': {'BOTTOM': 0, 'LEFT': 0, 'RIGHT': 0, 'TOP': 0},
            'PADDING': False,
            'WEIGHTS': 'Aryn/deformable-detr-DocLayNet/model.safetensors',
            'WEIGHTS_TS': 'layout/d2_model_0829999_layout_inf_only.ts'},
 'LAYOUT_LINK': {'CHILD_CATEGORIES': [<LayoutType.CAPTION>],
                 'PARENTAL_CATEGORIES': [<LayoutType.FIGURE>, <LayoutType.TABLE>]},
 'LAYOUT_NMS_PAIRS': {'COMBINATIONS': [[<LayoutType.TABLE>, <LayoutType.TITLE>],
                                       [<LayoutType.TABLE>, <LayoutType.TEXT>],
                                       [<LayoutType.TABLE>, <LayoutType.KEY_VALUE_AREA>],
                                       [<LayoutType.TABLE>, <LayoutType.LIST_ITEM>],
                                       [<LayoutType.TABLE>, <LayoutType.LIST>],
                                       [<LayoutType.TABLE>, <LayoutType.FIGURE>],
                                       [<LayoutType.TITLE>, <LayoutType.TEXT>],
                                       [<LayoutType.TEXT>, <LayoutType.KEY_VALUE_AREA>],
                                       [<LayoutType.TEXT>, <LayoutType.LIST_ITEM>],
                                       [<LayoutType.TEXT>, <LayoutType.CAPTION>],
                                       [<LayoutType.KEY_VALUE_AREA>, <LayoutType.LIST_ITEM>],
                                       [<LayoutType.FIGURE>, <LayoutType.CAPTION>]],
                      'PRIORITY': [<LayoutType.TABLE>, <LayoutType.TABLE>, <LayoutType.TABLE>,
                                   <LayoutType.TABLE>, <LayoutType.TABLE>, <LayoutType.TABLE>,
                                   <LayoutType.TEXT>, <LayoutType.TEXT>, None, <LayoutType.CAPTION>,
                                   <LayoutType.KEY_VALUE_AREA>, <LayoutType.FIGURE>],
                      'THRESHOLDS': [0.001, 0.01, 0.01, 0.001, 0.01, 0.01, 0.05, 0.01, 0.01, 0.01,
                                     0.01, 0.001]},
 'LIB': 'PT',
 'LM_LANGUAGE_DETECT_CLASS': {'WEIGHTS': None},
 'LM_SEQUENCE_CLASS': {'USE_OTHER_AS_DEFAULT_CATEGORY': False, 'WEIGHTS': None},
 'LM_TOKEN_CLASS': {'SEGMENT_POSITIONS': None,
                    'SLIDING_WINDOW_STRIDE': 0,
                    'USE_OTHER_AS_DEFAULT_CATEGORY': False,
                    'WEIGHTS': None},
 'OCR': {'CONFIG': {'TESSERACT': 'dd/conf_tesseract.yaml'},
         'USE_DOCTR': False,
         'USE_TESSERACT': False,
         'USE_TEXTRACT': False,
         'WEIGHTS': {'DOCTR_RECOGNITION': 'doctr/crnn_vgg16_bn/crnn_vgg16_bn-0417f351.pt',
                     'DOCTR_WORD': 'doctr/db_resnet50/db_resnet50-ac60cadc.pt'}},
 'PDF_MINER': {'X_TOLERANCE': 3, 'Y_TOLERANCE': 3},
 'ROTATOR': {'MODEL': 'tesseract'},
 'SEGMENTATION': {'ASSIGNMENT_RULE': 'ioa',
                  'CELL_NAMES': [<CellType.COLUMN_HEADER>, <CellType.BODY>, <LayoutType.CELL>],
                  'FULL_TABLE_TILING': True,
                  'ITEM_NAMES': [<LayoutType.ROW>, <LayoutType.COLUMN>],
                  'PUBTABLES_CELL_NAMES': [<LayoutType.CELL>],
                  'PUBTABLES_ITEM_HEADER_CELL_NAMES': [<CellType.COLUMN_HEADER>,
                                                       <CellType.ROW_HEADER>,
                                                       <CellType.PROJECTED_ROW_HEADER>],
                  'PUBTABLES_ITEM_HEADER_THRESHOLDS': [0.6, 0.0001],
                  'PUBTABLES_ITEM_NAMES': [<LayoutType.ROW>, <LayoutType.COLUMN>],
                  'PUBTABLES_SPANNING_CELL_NAMES': [<CellType.SPANNING>],
                  'PUBTABLES_SUB_ITEM_NAMES': [<CellType.ROW_NUMBER>, <CellType.COLUMN_NUMBER>],
                  'REMOVE_IOU_THRESHOLD_COLS': 0.2,
                  'REMOVE_IOU_THRESHOLD_ROWS': 0.2,
                  'STRETCH_RULE': 'equal',
                  'SUB_ITEM_NAMES': [<CellType.ROW_NUMBER>, <CellType.COLUMN_NUMBER>],
                  'TABLE_NAME': <LayoutType.TABLE>,
                  'THRESHOLD_COLS': 0.4,
                  'THRESHOLD_ROWS': 0.4},
 'TEXT_CONTAINER': <LayoutType.WORD>,
 'TEXT_ORDERING': {'BROKEN_LINE_TOLERANCE': 0.003,
                   'FLOATING_TEXT_BLOCK_CATEGORIES': (<LayoutType.TEXT>, <LayoutType.TITLE>,
                                                      <LayoutType.LIST>,
                                                      <LayoutType.KEY_VALUE_AREA>),
                   'HEIGHT_TOLERANCE': 2.0,
                   'INCLUDE_RESIDUAL_TEXT_CONTAINER': True,
                   'PARAGRAPH_BREAK': 0.035,
                   'STARTING_POINT_TOLERANCE': 0.005,
                   'TEXT_BLOCK_CATEGORIES': (<LayoutType.TEXT>, <LayoutType.TITLE>,
                                             <LayoutType.LIST_ITEM>, <LayoutType.LIST>,
                                             <LayoutType.CAPTION>, <LayoutType.PAGE_HEADER>,
                                             <LayoutType.PAGE_FOOTER>, <LayoutType.PAGE_NUMBER>,
                                             <LayoutType.MARK>, <LayoutType.KEY_VALUE_AREA>,
                                             <LayoutType.FIGURE>, <CellType.SPANNING>,
                                             <LayoutType.CELL>)},
 'USE_LAYOUT': True,
 'USE_LAYOUT_LINK': False,
 'USE_LAYOUT_NMS': True,
 'USE_LINE_MATCHER': False,
 'USE_LM_LANGUAGE_DETECTION': False,
 'USE_LM_SEQUENCE_CLASS': False,
 'USE_LM_TOKEN_CLASS': False,
 'USE_OCR': False,
 'USE_PDF_MINER': True,
 'USE_ROTATOR': False,
 'USE_TABLE_REFINEMENT': False,
 'USE_TABLE_SEGMENTATION': True,
 'WORD_MATCHING': {'MAX_PARENT_ONLY': True,
                   'PARENTAL_CATEGORIES': (<LayoutType.TEXT>, <LayoutType.TITLE>,
                                           <LayoutType.LIST_ITEM>, <LayoutType.LIST>,
                                           <LayoutType.CAPTION>, <LayoutType.PAGE_HEADER>,
                                           <LayoutType.PAGE_FOOTER>, <LayoutType.PAGE_NUMBER>,
                                           <LayoutType.MARK>, <LayoutType.KEY_VALUE_AREA>,
                                           <LayoutType.FIGURE>, <CellType.SPANNING>,
                                           <LayoutType.CELL>),
                   'RULE': 'ioa',
                   'THRESHOLD': 0.3}}
You are using a model of type deformable_detr to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
[0407 13:00.14 @helpers.py:188]  INF  Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
You are using a model of type table-transformer to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
[0407 13:00.15 @helpers.py:188]  INF  Loading pretrained weights from url (https://download.pytorch.org/models/resnet18-5c106cde.pth)
[0407 13:00.15 @order.py:815]  WRN  In most cases floating_text_block_categories must be a subset of text_block_categories. Adding categories to floating_text_block_categories, that do not belong to text_block_categories makes only sense for categories set have CHILD relationships with annotations that belong to text_block_categories.

Analyzer listo: DoctectionPipe

## Extracción de tablas

In [45]:
def extract_tables_from_pdf(pdf_path: Path, analyzer) -> dict:
    """
    Procesa un PDF con deepdoctection y devuelve un documento con el
    formato del ground truth (paper_title, num_tables, tables[]).
    """
    paper_title = pdf_path.stem
    print(f"\n{'='*70}")
    print(f"Procesando: {paper_title}")
    print(f"{'='*70}")

    df = analyzer.analyze(path=str(pdf_path))
    df.reset_state()

    # Recolectar todas las tablas en orden de aparición (página, luego orden en página)
    all_tables_raw = []
    for page in df:
        for table in page.tables:
            all_tables_raw.append((page.page_number, table))

    print(f"Tablas detectadas: {len(all_tables_raw)}")

    tables_json = []
    table_counter = 0

    for page_num, table in all_tables_raw:
        html_str = table.html

        if not html_str:
            print(f"  [SKIP] página {page_num}: sin HTML")
            continue

        columns, data_rows = parse_table_html(html_str)

        if columns is None or not data_rows:
            print(f"  [SKIP] página {page_num}: no parseada o sin filas de datos")
            continue

        table_counter += 1
        table_id = f"table_{table_counter}"
        expected_rows = len(data_rows)
        expected_cols = len(columns)

        print(f"  [{table_id}] página {page_num} → {expected_rows} filas × {expected_cols} cols")
        print(f"    Columnas: {columns}")

        tables_json.append({
            "table_id": table_id,
            "page": page_num,
            "evaluation": {
                "expected_rows": expected_rows,
                "expected_cols": expected_cols,
                "columns": columns
            },
            "rows": data_rows
        })

    document = {
        "paper_title": paper_title,
        "num_tables": len(tables_json),
        "tables": tables_json
    }

    print(f"  → Tablas incluidas en ground truth: {len(tables_json)}")
    return document

## Ejecutar en los 5 papers

In [46]:
documents = []

for pdf_path in PDF_FILES:
    doc = extract_tables_from_pdf(pdf_path, analyzer)
    documents.append(doc)

ground_truth = {"documents": documents}

print(f"\n{'='*70}")
print("RESUMEN FINAL")
print(f"{'='*70}")
total_tables = sum(d['num_tables'] for d in documents)
for d in documents:
    print(f"  {d['paper_title'][:60]:60s} → {d['num_tables']} tablas")
print(f"\nTotal tablas extraídas: {total_tables}")

[0407 13:00.15 @doctectionpipe.py:118]  INF  Processing Adaptive Margin Ranking Loss for Knowledge Graph Embeddings via a Correntropy Objective Function_0.pdf

======================================================================
Procesando: Adaptive Margin Ranking Loss for Knowledge Graph Embeddings via a Correntropy Objective Function
======================================================================

[0407 13:00.30 @context.py:156]  INF  ImageLayoutService total: 14.8391 sec.
[0407 13:00.30 @context.py:156]  INF  AnnotationNmsService total: 0.0019 sec.
[0407 13:00.30 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:00.30 @context.py:156]  INF  PubtablesSegmentationService total: 0.0004 sec.
[0407 13:00.30 @context.py:156]  INF  TextExtractionService total: 0.1303 sec.
[0407 13:00.30 @context.py:156]  INF  MatchingService total: 0.0046 sec.
[0407 13:00.30 @context.py:156]  INF  TextOrderService total: 0.0098 sec.
[0407 13:00.30 @doctectionpipe.py:118]  INF  Processing Adaptive Margin Ranking Loss for Knowledge Graph Embeddings via a Correntropy Objective Function_1.pdf
[0407 13:00.32 @context.py:156]  INF  ImageLayoutService total: 1.8256 sec.
[0407 13:00.32 @context.py:156]  INF  AnnotationNmsService total: 0.0009 sec.
[0407 13:00.32 @context.py:156]  INF  SubImageLayoutService total: 0.0 sec.
[0407 13:00.32 @context.py:156]  INF  PubtablesSegmentationService total: 0.0002 sec.
[0407 13:00.33 @context.py:156]  INF  TextExtractionService total: 0.7946 sec.
[0407 13:00.33 @context.py:156]  INF  MatchingService total: 0.0043 sec.
[0407 13:00.33 @context.py:156]  INF  TextOrderService total: 0.0149 sec.
[0407 13:00.33 @doctectionpipe.py:118]  INF  Processing Adaptive Margin Ranking Loss for Knowledge Graph Embeddings via a Correntropy Objective Function_2.pdf
[0407 13:00.35 @context.py:156]  INF  ImageLayoutService total: 1.9567 sec.
[0407 13:00.35 @context.py:156]  INF  AnnotationNmsService total: 0.0021 sec.
[0407 13:00.35 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:00.35 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:00.35 @context.py:156]  INF  TextExtractionService total: 0.1659 sec.
[0407 13:00.35 @context.py:156]  INF  MatchingService total: 0.0051 sec.
[0407 13:00.35 @context.py:156]  INF  TextOrderService total: 0.023 sec.
[0407 13:00.35 @doctectionpipe.py:118]  INF  Processing Adaptive Margin Ranking Loss for Knowledge Graph Embeddings via a Correntropy Objective Function_3.pdf
[0407 13:00.37 @context.py:156]  INF  ImageLayoutService total: 1.7856 sec.
[0407 13:00.37 @context.py:156]  INF  AnnotationNmsService total: 0.0014 sec.
[0407 13:00.37 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:00.37 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:00.37 @context.py:156]  INF  TextExtractionService total: 0.1163 sec.
[0407 13:00.37 @context.py:156]  INF  MatchingService total: 0.003 sec.
[0407 13:00.37 @context.py:156]  INF  TextOrderService total: 0.0099 sec.
[0407 13:00.37 @doctectionpipe.py:118]  INF  Processing Adaptive Margin Ranking Loss for Knowledge Graph Embeddings via a Correntropy Objective Function_4.pdf
[0407 13:00.39 @context.py:156]  INF  ImageLayoutService total: 1.7521 sec.
[0407 13:00.39 @context.py:156]  INF  AnnotationNmsService total: 0.0014 sec.
[0407 13:00.43 @context.py:156]  INF  SubImageLayoutService total: 4.4467 sec.
[0407 13:00.43 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:00.43 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:00.43 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:00.43 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:00.44 @context.py:156]  INF  PubtablesSegmentationService total: 0.3532 sec.
[0407 13:00.44 @context.py:156]  INF  TextExtractionService total: 0.2506 sec.
[0407 13:00.44 @context.py:156]  INF  MatchingService total: 0.01 sec.
[0407 13:00.44 @context.py:156]  INF  TextOrderService total: 0.099 sec.
[0407 13:00.44 @doctectionpipe.py:118]  INF  Processing Adaptive Margin Ranking Loss for Knowledge Graph Embeddings via a Correntropy Objective Function_5.pdf
[0407 13:00.46 @context.py:156]  INF  ImageLayoutService total: 2.0091 sec.
[0407 13:00.46 @context.py:156]  INF  AnnotationNmsService total: 0.0017 sec.
[0407 13:00.46 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:00.46 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:00.46 @context.py:156]  INF  TextExtractionService total: 0.1648 sec.
[0407 13:00.46 @context.py:156]  INF  MatchingService total: 0.0063 sec.
[0407 13:00.46 @context.py:156]  INF  TextOrderService total: 0.0228 sec.
[0407 13:00.46 @doctectionpipe.py:118]  INF  Processing Adaptive Margin Ranking Loss for Knowledge Graph Embeddings via a Correntropy Objective Function_6.pdf
[0407 13:00.48 @context.py:156]  INF  ImageLayoutService total: 1.7791 sec.
[0407 13:00.48 @context.py:156]  INF  AnnotationNmsService total: 0.0011 sec.
[0407 13:00.48 @context.py:156]  INF  SubImageLayoutService total: 0.0 sec.
[0407 13:00.48 @context.py:156]  INF  PubtablesSegmentationService total: 0.0 sec.
[0407 13:00.48 @context.py:156]  INF  TextExtractionService total: 0.0049 sec.
[0407 13:00.48 @context.py:156]  INF  MatchingService total: 0.0006 sec.
[0407 13:00.48 @context.py:156]  INF  TextOrderService total: 0.0003 sec.
[0407 13:00.48 @view.py:789]  WRN  html construction not possible

Tablas detectadas: 2
  [table_1] página 4 → 7 filas × 3 cols
    Columnas: ['Data', 'FB15k', 'wn18']
  [table_2] página 4 → 18 filas × 9 cols
    Columnas: ['Dataset', 'WN18_Mean_raw', 'WN18_Mean_filter', 'WN18_Hits@10(%)_raw', 'WN18_Hits@10(%)_filter', 'FB15k_Mean_raw', 'FB15k_Mean_filter', 'FB15k_Hits@10(%)_raw', 'FB15k_Hits@10(%)_filter']
  → Tablas incluidas en ground truth: 2

======================================================================
Procesando: Adversarial Contrastive Estimation
======================================================================

[0407 13:00.48 @doctectionpipe.py:118]  INF  Processing Adversarial Contrastive Estimation_0.pdf
[0407 13:00.54 @context.py:156]  INF  ImageLayoutService total: 5.8708 sec.
[0407 13:00.54 @context.py:156]  INF  AnnotationNmsService total: 0.0029 sec.
[0407 13:00.54 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:00.54 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:00.55 @context.py:156]  INF  TextExtractionService total: 0.6357 sec.
[0407 13:00.55 @context.py:156]  INF  MatchingService total: 0.0115 sec.
[0407 13:00.55 @context.py:156]  INF  TextOrderService total: 0.0222 sec.
[0407 13:00.55 @doctectionpipe.py:118]  INF  Processing Adversarial Contrastive Estimation_1.pdf
[0407 13:00.58 @context.py:156]  INF  ImageLayoutService total: 3.3577 sec.
[0407 13:00.58 @context.py:156]  INF  AnnotationNmsService total: 0.0054 sec.
[0407 13:00.58 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:00.58 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:00.59 @context.py:156]  INF  TextExtractionService total: 0.3178 sec.
[0407 13:00.59 @context.py:156]  INF  MatchingService total: 0.0124 sec.
[0407 13:00.59 @context.py:156]  INF  TextOrderService total: 0.0288 sec.
[0407 13:00.59 @doctectionpipe.py:118]  INF  Processing Adversarial Contrastive Estimation_2.pdf
[0407 13:01.01 @context.py:156]  INF  ImageLayoutService total: 2.153 sec.
[0407 13:01.01 @context.py:156]  INF  AnnotationNmsService total: 0.0032 sec.
[0407 13:01.01 @context.py:156]  INF  SubImageLayoutService total: 0.0002 sec.
[0407 13:01.01 @context.py:156]  INF  PubtablesSegmentationService total: 0.0002 sec.
[0407 13:01.01 @context.py:156]  INF  TextExtractionService total: 0.3097 sec.
[0407 13:01.01 @context.py:156]  INF  MatchingService total: 0.0109 sec.
[0407 13:01.01 @context.py:156]  INF  TextOrderService total: 0.03 sec.
[0407 13:01.01 @doctectionpipe.py:118]  INF  Processing Adversarial Contrastive Estimation_3.pdf
[0407 13:01.04 @context.py:156]  INF  ImageLayoutService total: 2.28 sec.
[0407 13:01.04 @context.py:156]  INF  AnnotationNmsService total: 0.0016 sec.
[0407 13:01.04 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:01.04 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:01.04 @context.py:156]  INF  TextExtractionService total: 0.3337 sec.
[0407 13:01.04 @context.py:156]  INF  MatchingService total: 0.0115 sec.
[0407 13:01.04 @context.py:156]  INF  TextOrderService total: 0.0273 sec.
[0407 13:01.04 @doctectionpipe.py:118]  INF  Processing Adversarial Contrastive Estimation_4.pdf
[0407 13:01.06 @context.py:156]  INF  ImageLayoutService total: 2.1028 sec.
[0407 13:01.06 @context.py:156]  INF  AnnotationNmsService total: 0.0014 sec.
[0407 13:01.06 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:01.06 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:01.07 @context.py:156]  INF  TextExtractionService total: 0.586 sec.
[0407 13:01.07 @context.py:156]  INF  MatchingService total: 0.0112 sec.
[0407 13:01.07 @context.py:156]  INF  TextOrderService total: 0.0421 sec.
[0407 13:01.07 @doctectionpipe.py:118]  INF  Processing Adversarial Contrastive Estimation_5.pdf
[0407 13:01.09 @context.py:156]  INF  ImageLayoutService total: 2.2949 sec.
[0407 13:01.09 @context.py:156]  INF  AnnotationNmsService total: 0.0017 sec.
[0407 13:01.09 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:01.09 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:01.10 @context.py:156]  INF  TextExtractionService total: 0.3023 sec.
[0407 13:01.10 @context.py:156]  INF  MatchingService total: 0.0094 sec.
[0407 13:01.10 @context.py:156]  INF  TextOrderService total: 0.0308 sec.
[0407 13:01.10 @doctectionpipe.py:118]  INF  Processing Adversarial Contrastive Estimation_6.pdf
[0407 13:01.12 @context.py:156]  INF  ImageLayoutService total: 2.1319 sec.
[0407 13:01.12 @context.py:156]  INF  AnnotationNmsService total: 0.0019 sec.
[0407 13:01.12 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:01.12 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:01.12 @context.py:156]  INF  TextExtractionService total: 0.2116 sec.
[0407 13:01.12 @context.py:156]  INF  MatchingService total: 0.0091 sec.
[0407 13:01.12 @context.py:156]  INF  TextOrderService total: 0.0209 sec.
[0407 13:01.12 @doctectionpipe.py:118]  INF  Processing Adversarial Contrastive Estimation_7.pdf
[0407 13:01.14 @context.py:156]  INF  ImageLayoutService total: 2.1699 sec.
[0407 13:01.14 @context.py:156]  INF  AnnotationNmsService total: 0.0016 sec.
[0407 13:01.15 @context.py:156]  INF  SubImageLayoutService total: 0.7151 sec.
[0407 13:01.15 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:01.15 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:01.15 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:01.15 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:01.15 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:01.15 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:01.15 @context.py:156]  INF  PubtablesSegmentationService total: 0.0451 sec.
[0407 13:01.15 @context.py:156]  INF  TextExtractionService total: 0.2228 sec.
[0407 13:01.15 @context.py:156]  INF  MatchingService total: 0.0083 sec.
[0407 13:01.15 @context.py:156]  INF  TextOrderService total: 0.0447 sec.
[0407 13:01.15 @doctectionpipe.py:118]  INF  Processing Adversarial Contrastive Estimation_8.pdf
[0407 13:01.18 @context.py:156]  INF  ImageLayoutService total: 2.2693 sec.
[0407 13:01.18 @context.py:156]  INF  AnnotationNmsService total: 0.0039 sec.
[0407 13:01.18 @context.py:156]  INF  SubImageLayoutService total: 0.4462 sec.
[0407 13:01.18 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:01.18 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:01.18 @context.py:156]  INF  PubtablesSegmentationService total: 0.0185 sec.
[0407 13:01.19 @context.py:156]  INF  TextExtractionService total: 0.2879 sec.
[0407 13:01.19 @context.py:156]  INF  MatchingService total: 0.01 sec.
[0407 13:01.19 @context.py:156]  INF  TextOrderService total: 0.0403 sec.
[0407 13:01.19 @doctectionpipe.py:118]  INF  Processing Adversarial Contrastive Estimation_9.pdf
[0407 13:01.21 @context.py:156]  INF  ImageLayoutService total: 1.9611 sec.
[0407 13:01.21 @context.py:156]  INF  AnnotationNmsService total: 0.0026 sec.
[0407 13:01.21 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:01.21 @context.py:156]  INF  PubtablesSegmentationService total: 0.0002 sec.
[0407 13:01.21 @context.py:156]  INF  TextExtractionService total: 0.5172 sec.
[0407 13:01.21 @context.py:156]  INF  MatchingService total: 0.0093 sec.
[0407 13:01.21 @context.py:156]  INF  TextOrderService total: 0.0382 sec.
[0407 13:01.21 @doctectionpipe.py:118]  INF  Processing Adversarial Contrastive Estimation_10.pdf
[0407 13:01.24 @context.py:156]  INF  ImageLayoutService total: 2.6856 sec.
[0407 13:01.24 @context.py:156]  INF  AnnotationNmsService total: 0.0019 sec.
[0407 13:01.24 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:01.24 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:01.24 @context.py:156]  INF  TextExtractionService total: 0.2674 sec.
[0407 13:01.24 @context.py:156]  INF  MatchingService total: 0.0107 sec.
[0407 13:01.24 @context.py:156]  INF  TextOrderService total: 0.0424 sec.
[0407 13:01.24 @doctectionpipe.py:118]  INF  Processing Adversarial Contrastive Estimation_11.pdf
[0407 13:01.26 @context.py:156]  INF  ImageLayoutService total: 2.1297 sec.
[0407 13:01.26 @context.py:156]  INF  AnnotationNmsService total: 0.0013 sec.
[0407 13:01.26 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:01.26 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:01.26 @context.py:156]  INF  TextExtractionService total: 0.0319 sec.
[0407 13:01.26 @context.py:156]  INF  MatchingService total: 0.0029 sec.
[0407 13:01.26 @context.py:156]  INF  TextOrderService total: 0.004 sec.
[0407 13:01.27 @doctectionpipe.py:118]  INF  Processing Binarized Knowledge Graph Embeddings_0.pdf

Tablas detectadas: 4
  [table_1] página 7 → 9 filas × 3 cols
    Columnas: ['', 'RW', 'WS353']
  [table_2] página 7 → 4 filas × 6 cols
    Columnas: ['', 'Queen', 'King', 'Computer', 'Man', 'Woman']
  [table_3] página 7 → 2 filas × 2 cols
    Columnas: ['Method', 'Accuracy(%)']
  [table_4] página 8 → 8 filas × 3 cols
    Columnas: ['', 'MRR', 'hit@10']
  → Tablas incluidas en ground truth: 4

======================================================================
Procesando: Binarized Knowledge Graph Embeddings
======================================================================

[0407 13:01.29 @context.py:156]  INF  ImageLayoutService total: 2.2867 sec.
[0407 13:01.29 @context.py:156]  INF  AnnotationNmsService total: 0.0019 sec.
[0407 13:01.29 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:01.29 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:01.29 @context.py:156]  INF  TextExtractionService total: 0.1544 sec.
[0407 13:01.29 @context.py:156]  INF  MatchingService total: 0.0072 sec.
[0407 13:01.29 @context.py:156]  INF  TextOrderService total: 0.0151 sec.
[0407 13:01.29 @doctectionpipe.py:118]  INF  Processing Binarized Knowledge Graph Embeddings_1.pdf
[0407 13:01.31 @context.py:156]  INF  ImageLayoutService total: 1.8105 sec.
[0407 13:01.31 @context.py:156]  INF  AnnotationNmsService total: 0.0009 sec.
[0407 13:01.31 @context.py:156]  INF  SubImageLayoutService total: 0.0 sec.
[0407 13:01.31 @context.py:156]  INF  PubtablesSegmentationService total: 0.0 sec.
[0407 13:01.31 @context.py:156]  INF  TextExtractionService total: 0.2351 sec.
[0407 13:01.31 @context.py:156]  INF  MatchingService total: 0.0085 sec.
[0407 13:01.31 @context.py:156]  INF  TextOrderService total: 0.0175 sec.
[0407 13:01.31 @doctectionpipe.py:118]  INF  Processing Binarized Knowledge Graph Embeddings_2.pdf
[0407 13:01.33 @context.py:156]  INF  ImageLayoutService total: 1.8388 sec.
[0407 13:01.33 @context.py:156]  INF  AnnotationNmsService total: 0.0013 sec.
[0407 13:01.33 @context.py:156]  INF  SubImageLayoutService total: 0.0 sec.
[0407 13:01.33 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:01.33 @context.py:156]  INF  TextExtractionService total: 0.2016 sec.
[0407 13:01.33 @context.py:156]  INF  MatchingService total: 0.0073 sec.
[0407 13:01.33 @context.py:156]  INF  TextOrderService total: 0.015 sec.
[0407 13:01.33 @doctectionpipe.py:118]  INF  Processing Binarized Knowledge Graph Embeddings_3.pdf
[0407 13:01.35 @context.py:156]  INF  ImageLayoutService total: 1.771 sec.
[0407 13:01.35 @context.py:156]  INF  AnnotationNmsService total: 0.0019 sec.
[0407 13:01.35 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:01.35 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:01.35 @context.py:156]  INF  TextExtractionService total: 0.2097 sec.
[0407 13:01.35 @context.py:156]  INF  MatchingService total: 0.007 sec.
[0407 13:01.35 @context.py:156]  INF  TextOrderService total: 0.0257 sec.
[0407 13:01.35 @doctectionpipe.py:118]  INF  Processing Binarized Knowledge Graph Embeddings_4.pdf
[0407 13:01.37 @context.py:156]  INF  ImageLayoutService total: 1.7984 sec.
[0407 13:01.37 @context.py:156]  INF  AnnotationNmsService total: 0.0022 sec.
[0407 13:01.37 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:01.37 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:01.38 @context.py:156]  INF  TextExtractionService total: 0.5178 sec.
[0407 13:01.38 @context.py:156]  INF  MatchingService total: 0.0063 sec.
[0407 13:01.38 @context.py:156]  INF  TextOrderService total: 0.0194 sec.
[0407 13:01.38 @doctectionpipe.py:118]  INF  Processing Binarized Knowledge Graph Embeddings_5.pdf
[0407 13:01.40 @context.py:156]  INF  ImageLayoutService total: 1.9263 sec.
[0407 13:01.40 @context.py:156]  INF  AnnotationNmsService total: 0.0013 sec.
[0407 13:01.40 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:01.40 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:01.40 @context.py:156]  INF  TextExtractionService total: 0.1658 sec.
[0407 13:01.40 @context.py:156]  INF  MatchingService total: 0.0062 sec.
[0407 13:01.40 @context.py:156]  INF  TextOrderService total: 0.0266 sec.
[0407 13:01.40 @doctectionpipe.py:118]  INF  Processing Binarized Knowledge Graph Embeddings_6.pdf
[0407 13:01.42 @context.py:156]  INF  ImageLayoutService total: 1.7677 sec.
[0407 13:01.42 @context.py:156]  INF  AnnotationNmsService total: 0.0009 sec.
[0407 13:01.42 @context.py:156]  INF  SubImageLayoutService total: 0.0 sec.
[0407 13:01.42 @context.py:156]  INF  PubtablesSegmentationService total: 0.0 sec.
[0407 13:01.42 @context.py:156]  INF  TextExtractionService total: 0.1735 sec.
[0407 13:01.42 @context.py:156]  INF  MatchingService total: 0.0072 sec.
[0407 13:01.42 @context.py:156]  INF  TextOrderService total: 0.0374 sec.
[0407 13:01.42 @doctectionpipe.py:118]  INF  Processing Binarized Knowledge Graph Embeddings_7.pdf
[0407 13:01.44 @context.py:156]  INF  ImageLayoutService total: 1.8041 sec.
[0407 13:01.44 @context.py:156]  INF  AnnotationNmsService total: 0.0019 sec.
[0407 13:01.44 @context.py:156]  INF  SubImageLayoutService total: 0.5555 sec.
[0407 13:01.44 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:01.44 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:01.44 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:01.44 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:01.44 @context.py:156]  INF  PubtablesSegmentationService total: 0.1911 sec.
[0407 13:01.45 @context.py:156]  INF  TextExtractionService total: 0.2716 sec.
[0407 13:01.45 @context.py:156]  INF  MatchingService total: 0.0097 sec.
[0407 13:01.45 @context.py:156]  INF  TextOrderService total: 0.0876 sec.
[0407 13:01.45 @doctectionpipe.py:118]  INF  Processing Binarized Knowledge Graph Embeddings_8.pdf
[0407 13:01.47 @context.py:156]  INF  ImageLayoutService total: 1.8737 sec.
[0407 13:01.47 @context.py:156]  INF  AnnotationNmsService total: 0.0014 sec.
[0407 13:01.47 @context.py:156]  INF  SubImageLayoutService total: 0.2876 sec.
[0407 13:01.47 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:01.47 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:01.47 @context.py:156]  INF  PubtablesSegmentationService total: 0.0869 sec.
[0407 13:01.47 @context.py:156]  INF  TextExtractionService total: 0.195 sec.
[0407 13:01.47 @context.py:156]  INF  MatchingService total: 0.0083 sec.
[0407 13:01.47 @context.py:156]  INF  TextOrderService total: 0.0489 sec.
[0407 13:01.47 @doctectionpipe.py:118]  INF  Processing Binarized Knowledge Graph Embeddings_9.pdf
[0407 13:01.49 @context.py:156]  INF  ImageLayoutService total: 1.7648 sec.
[0407 13:01.49 @context.py:156]  INF  AnnotationNmsService total: 0.0009 sec.
[0407 13:01.49 @context.py:156]  INF  SubImageLayoutService total: 0.2154 sec.
[0407 13:01.49 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:01.49 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:01.49 @context.py:156]  INF  PubtablesSegmentationService total: 0.0589 sec.
[0407 13:01.50 @context.py:156]  INF  TextExtractionService total: 0.1875 sec.
[0407 13:01.50 @context.py:156]  INF  MatchingService total: 0.008 sec.
[0407 13:01.50 @context.py:156]  INF  TextOrderService total: 0.0469 sec.
[0407 13:01.50 @doctectionpipe.py:118]  INF  Processing Binarized Knowledge Graph Embeddings_10.pdf
[0407 13:01.51 @context.py:156]  INF  ImageLayoutService total: 1.7565 sec.
[0407 13:01.51 @context.py:156]  INF  AnnotationNmsService total: 0.0008 sec.
[0407 13:01.51 @context.py:156]  INF  SubImageLayoutService total: 0.0 sec.
[0407 13:01.51 @context.py:156]  INF  PubtablesSegmentationService total: 0.0 sec.
[0407 13:01.52 @context.py:156]  INF  TextExtractionService total: 0.1183 sec.
[0407 13:01.52 @context.py:156]  INF  MatchingService total: 0.0053 sec.
[0407 13:01.52 @context.py:156]  INF  TextOrderService total: 0.0095 sec.
[0407 13:01.52 @doctectionpipe.py:118]  INF  Processing Binarized Knowledge Graph Embeddings_11.pdf
[0407 13:01.53 @context.py:156]  INF  ImageLayoutService total: 1.742 sec.
[0407 13:01.53 @context.py:156]  INF  AnnotationNmsService total: 0.0011 sec.
[0407 13:01.54 @context.py:156]  INF  SubImageLayoutService total: 0.2199 sec.
[0407 13:01.54 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:01.54 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:01.54 @context.py:156]  INF  PubtablesSegmentationService total: 0.0068 sec.
[0407 13:01.54 @context.py:156]  INF  TextExtractionService total: 0.1095 sec.
[0407 13:01.54 @context.py:156]  INF  MatchingService total: 0.0052 sec.
[0407 13:01.54 @context.py:156]  INF  TextOrderService total: 0.0144 sec.
[0407 13:01.54 @doctectionpipe.py:118]  INF  Processing Binarized Knowledge Graph Embeddings_12.pdf
[0407 13:01.56 @context.py:156]  INF  ImageLayoutService total: 1.8005 sec.
[0407 13:01.56 @context.py:156]  INF  AnnotationNmsService total: 0.0014 sec.
[0407 13:01.56 @context.py:156]  INF  SubImageLayoutService total: 0.0 sec.
[0407 13:01.56 @context.py:156]  INF  PubtablesSegmentationService total: 0.0 sec.
[0407 13:01.56 @context.py:156]  INF  TextExtractionService total: 0.4178 sec.
[0407 13:01.56 @context.py:156]  INF  MatchingService total: 0.0078 sec.
[0407 13:01.56 @context.py:156]  INF  TextOrderService total: 0.0208 sec.
[0407 13:01.56 @doctectionpipe.py:118]  INF  Processing Binarized Knowledge Graph Embeddings_13.pdf
[0407 13:01.58 @context.py:156]  INF  ImageLayoutService total: 1.786 sec.
[0407 13:01.58 @context.py:156]  INF  AnnotationNmsService total: 0.0013 sec.
[0407 13:01.58 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:01.58 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:01.58 @context.py:156]  INF  TextExtractionService total: 0.1853 sec.
[0407 13:01.58 @context.py:156]  INF  MatchingService total: 0.0082 sec.
[0407 13:01.58 @context.py:156]  INF  TextOrderService total: 0.0228 sec.
[0407 13:01.58 @doctectionpipe.py:118]  INF  Processing Binarized Knowledge Graph Embeddings_14.pdf
[0407 13:02.00 @context.py:156]  INF  ImageLayoutService total: 1.7745 sec.
[0407 13:02.00 @context.py:156]  INF  AnnotationNmsService total: 0.0009 sec.
[0407 13:02.00 @context.py:156]  INF  SubImageLayoutService total: 0.0 sec.
[0407 13:02.00 @context.py:156]  INF  PubtablesSegmentationService total: 0.0 sec.
[0407 13:02.00 @context.py:156]  INF  TextExtractionService total: 0.0385 sec.
[0407 13:02.00 @context.py:156]  INF  MatchingService total: 0.003 sec.
[0407 13:02.00 @context.py:156]  INF  TextOrderService total: 0.0044 sec.
[0407 13:02.00 @view.py:789]  WRN  html construction not possible
[0407 13:02.00 @view.py:789]  WRN  html construction not possible
[0407 13:02.00 @view.py:789]  WRN  html construction not possible
[0407 13:02.00 @view.py:789]  WRN  html construction not possible
[0407 13:02.00 @view.py:789]  WRN  html construction not possible
[0407 13:02.00 @view.py:789]  WRN  html construction not possible

Tablas detectadas: 5
  [table_1] página 7 → 11 filas × 9 cols
    Columnas: ['Models', 'WN18_MRR', 'WN18_Hits@_1', 'WN18_Hits@_3', 'WN18_Hits@_10', 'FB15k_MRR', 'FB15k_Hits@_1', 'FB15k_Hits@_3', 'FB15k_Hits@_10']
  [table_2] página 7 → 5 filas × 5 cols
    Columnas: ['', 'WN18', 'FB15k', 'WN18RR', 'FB15k-237']
  [table_3] página 8 → 8 filas × 9 cols
    Columnas: ['Models', 'WN18RR_MRR', 'WN18RR_Hits@_1', 'WN18RR_Hits@_3', 'WN18RR_Hits@_10', 'FB15k-237_MRR', 'FB15k-237_Hits@_1', 'FB15k-237_Hits@_3', 'FB15k-237_Hits@_10']

[0407 13:02.00 @view.py:789]  WRN  html construction not possible
[0407 13:02.00 @view.py:789]  WRN  html construction not possible
[0407 13:02.00 @view.py:789]  WRN  html construction not possible
[0407 13:02.00 @view.py:789]  WRN  html construction not possible
[0407 13:02.00 @view.py:789]  WRN  html construction not possible
[0407 13:02.00 @doctectionpipe.py:118]  INF  Processing HyperKG- Hyperbolic Knowledge Graph Embeddings for Knowledge Base Completion_0.pdf

  [table_4] página 9 → 10 filas × 5 cols
    Columnas: ['Model_DistMult*(D=200) 6,400 ComplEx*(D=200) 12,800_ConvE*(D=200)_CP(D=15) CP(D=50)', 'Bitsperentity_DistMult*(D=200) 6,400 ComplEx*(D=200) 12,800_6,400_960_3,200', 'Bitsperrelation_6,400_12,800_6,400_480_1,600', 'MRR_WN18RR_43.0_44.0_43.0_40.0_43.0', 'MRR_FB15k-237_24.1_24.7_32.5_22.0_24.8']
  [table_5] página 11 → 3 filas × 3 cols
    Columnas: ['', 'Accuracy', 'Modelsize']
  → Tablas incluidas en ground truth: 5

======================================================================
Procesando: HyperKG- Hyperbolic Knowledge Graph Embeddings for Knowledge Base Completion
======================================================================

[0407 13:02.02 @context.py:156]  INF  ImageLayoutService total: 1.7683 sec.
[0407 13:02.02 @context.py:156]  INF  AnnotationNmsService total: 0.0017 sec.
[0407 13:02.02 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:02.02 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:02.02 @context.py:156]  INF  TextExtractionService total: 0.1247 sec.
[0407 13:02.02 @context.py:156]  INF  MatchingService total: 0.0052 sec.
[0407 13:02.02 @context.py:156]  INF  TextOrderService total: 0.0102 sec.
[0407 13:02.02 @doctectionpipe.py:118]  INF  Processing HyperKG- Hyperbolic Knowledge Graph Embeddings for Knowledge Base Completion_1.pdf
[0407 13:02.04 @context.py:156]  INF  ImageLayoutService total: 1.8186 sec.
[0407 13:02.04 @context.py:156]  INF  AnnotationNmsService total: 0.0011 sec.
[0407 13:02.04 @context.py:156]  INF  SubImageLayoutService total: 0.0 sec.
[0407 13:02.04 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:02.04 @context.py:156]  INF  TextExtractionService total: 0.3371 sec.
[0407 13:02.04 @context.py:156]  INF  MatchingService total: 0.0096 sec.
[0407 13:02.04 @context.py:156]  INF  TextOrderService total: 0.0264 sec.
[0407 13:02.04 @doctectionpipe.py:118]  INF  Processing HyperKG- Hyperbolic Knowledge Graph Embeddings for Knowledge Base Completion_2.pdf
[0407 13:02.06 @context.py:156]  INF  ImageLayoutService total: 1.8786 sec.
[0407 13:02.06 @context.py:156]  INF  AnnotationNmsService total: 0.0014 sec.
[0407 13:02.06 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:02.06 @context.py:156]  INF  PubtablesSegmentationService total: 0.0002 sec.
[0407 13:02.07 @context.py:156]  INF  TextExtractionService total: 0.1971 sec.
[0407 13:02.07 @context.py:156]  INF  MatchingService total: 0.0063 sec.
[0407 13:02.07 @context.py:156]  INF  TextOrderService total: 0.0269 sec.
[0407 13:02.07 @doctectionpipe.py:118]  INF  Processing HyperKG- Hyperbolic Knowledge Graph Embeddings for Knowledge Base Completion_3.pdf
[0407 13:02.08 @context.py:156]  INF  ImageLayoutService total: 1.803 sec.
[0407 13:02.08 @context.py:156]  INF  AnnotationNmsService total: 0.0012 sec.
[0407 13:02.08 @context.py:156]  INF  SubImageLayoutService total: 0.0 sec.
[0407 13:02.08 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:02.09 @context.py:156]  INF  TextExtractionService total: 0.5282 sec.
[0407 13:02.09 @context.py:156]  INF  MatchingService total: 0.0082 sec.
[0407 13:02.09 @context.py:156]  INF  TextOrderService total: 0.0395 sec.
[0407 13:02.09 @doctectionpipe.py:118]  INF  Processing HyperKG- Hyperbolic Knowledge Graph Embeddings for Knowledge Base Completion_4.pdf
[0407 13:02.11 @context.py:156]  INF  ImageLayoutService total: 1.805 sec.
[0407 13:02.11 @context.py:156]  INF  AnnotationNmsService total: 0.0016 sec.
[0407 13:02.11 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:02.11 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:02.11 @context.py:156]  INF  TextExtractionService total: 0.2207 sec.
[0407 13:02.11 @context.py:156]  INF  MatchingService total: 0.0069 sec.
[0407 13:02.11 @context.py:156]  INF  TextOrderService total: 0.0144 sec.
[0407 13:02.11 @doctectionpipe.py:118]  INF  Processing HyperKG- Hyperbolic Knowledge Graph Embeddings for Knowledge Base Completion_5.pdf
[0407 13:02.13 @context.py:156]  INF  ImageLayoutService total: 1.7893 sec.
[0407 13:02.13 @context.py:156]  INF  AnnotationNmsService total: 0.0021 sec.
[0407 13:02.13 @context.py:156]  INF  SubImageLayoutService total: 0.303 sec.
[0407 13:02.13 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:02.13 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:02.13 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:02.13 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:02.13 @context.py:156]  INF  PubtablesSegmentationService total: 0.0187 sec.
[0407 13:02.14 @context.py:156]  INF  TextExtractionService total: 0.2522 sec.
[0407 13:02.14 @context.py:156]  INF  MatchingService total: 0.0082 sec.
[0407 13:02.14 @context.py:156]  INF  TextOrderService total: 0.0347 sec.
[0407 13:02.14 @doctectionpipe.py:118]  INF  Processing HyperKG- Hyperbolic Knowledge Graph Embeddings for Knowledge Base Completion_6.pdf
[0407 13:02.15 @context.py:156]  INF  ImageLayoutService total: 1.8174 sec.
[0407 13:02.16 @context.py:156]  INF  AnnotationNmsService total: 0.0014 sec.
[0407 13:02.16 @context.py:156]  INF  SubImageLayoutService total: 0.6502 sec.
[0407 13:02.16 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:02.16 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:02.16 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:02.16 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:02.16 @context.py:156]  INF  PubtablesSegmentationService total: 0.0433 sec.
[0407 13:02.16 @context.py:156]  INF  TextExtractionService total: 0.2475 sec.
[0407 13:02.16 @context.py:156]  INF  MatchingService total: 0.0081 sec.
[0407 13:02.17 @context.py:156]  INF  TextOrderService total: 0.0569 sec.
[0407 13:02.17 @doctectionpipe.py:118]  INF  Processing HyperKG- Hyperbolic Knowledge Graph Embeddings for Knowledge Base Completion_7.pdf
[0407 13:02.18 @context.py:156]  INF  ImageLayoutService total: 1.8317 sec.
[0407 13:02.18 @context.py:156]  INF  AnnotationNmsService total: 0.0012 sec.
[0407 13:02.18 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:02.18 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:02.19 @context.py:156]  INF  TextExtractionService total: 0.299 sec.
[0407 13:02.19 @context.py:156]  INF  MatchingService total: 0.0084 sec.
[0407 13:02.19 @context.py:156]  INF  TextOrderService total: 0.3734 sec.
[0407 13:02.19 @doctectionpipe.py:118]  INF  Processing HyperKG- Hyperbolic Knowledge Graph Embeddings for Knowledge Base Completion_8.pdf
[0407 13:02.21 @context.py:156]  INF  ImageLayoutService total: 1.8418 sec.
[0407 13:02.21 @context.py:156]  INF  AnnotationNmsService total: 0.0016 sec.
[0407 13:02.21 @context.py:156]  INF  SubImageLayoutService total: 0.0992 sec.
[0407 13:02.21 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:02.21 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:02.21 @context.py:156]  INF  PubtablesSegmentationService total: 0.0443 sec.
[0407 13:02.21 @context.py:156]  INF  TextExtractionService total: 0.2427 sec.
[0407 13:02.21 @context.py:156]  INF  MatchingService total: 0.0092 sec.
[0407 13:02.21 @context.py:156]  INF  TextOrderService total: 0.0631 sec.
[0407 13:02.21 @doctectionpipe.py:118]  INF  Processing HyperKG- Hyperbolic Knowledge Graph Embeddings for Knowledge Base Completion_9.pdf
[0407 13:02.23 @context.py:156]  INF  ImageLayoutService total: 1.7441 sec.
[0407 13:02.23 @context.py:156]  INF  AnnotationNmsService total: 0.0013 sec.
[0407 13:02.23 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:02.23 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:02.23 @context.py:156]  INF  TextExtractionService total: 0.1039 sec.
[0407 13:02.23 @context.py:156]  INF  MatchingService total: 0.0047 sec.
[0407 13:02.23 @context.py:156]  INF  TextOrderService total: 0.0137 sec.
[0407 13:02.23 @view.py:789]  WRN  html construction not possible
[0407 13:02.23 @view.py:789]  WRN  html construction not possible
[0407 13:02.23 @doctectionpipe.py:118]  INF  Processing Seq2RDF- An end-to-end application for deriving Triples from Natural Language Text_0.pdf

Tablas detectadas: 5
  [table_1] página 5 → 4 filas × 6 cols
    Columnas: ['Dataset', '|E|', '|R|', '#Train', '#Valid', '#Test']
  [table_2] página 5 → 1 filas × 3 cols
    Columnas: ['(a)', 'is a(x,y)∧part', 'of(y,z)→part of(x,z)']
  [table_3] página 6 → 6 filas × 6 cols
    Columnas: ['Method', 'Type', 'WN18RR_MRR', 'WN18RR_H@10', 'FB15k-237_MRR', 'FB15k-237_H@10']
  [table_4] página 6 → 2 filas × 5 cols
    Columnas: ['Method', 'MRR', 'WD H@10', 'WD MRR', '++ H@10']
  [table_5] página 8 → 8 filas × 9 cols
    Columnas: ['Dataset', 'Model', '# negsE', '# negsR', 'η', 'λ', 'n', 'γ,', 'β']
  → Tablas incluidas en ground truth: 5

======================================================================
Procesando: Seq2RDF- An end-to-end application for deriving Triples from Natural Language Text
======================================================================

[0407 13:02.25 @context.py:156]  INF  ImageLayoutService total: 1.782 sec.
[0407 13:02.25 @context.py:156]  INF  AnnotationNmsService total: 0.0011 sec.
[0407 13:02.25 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:02.25 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:02.25 @context.py:156]  INF  TextExtractionService total: 0.149 sec.
[0407 13:02.25 @context.py:156]  INF  MatchingService total: 0.0063 sec.
[0407 13:02.25 @context.py:156]  INF  TextOrderService total: 0.0158 sec.
[0407 13:02.25 @doctectionpipe.py:118]  INF  Processing Seq2RDF- An end-to-end application for deriving Triples from Natural Language Text_1.pdf
[0407 13:02.27 @context.py:156]  INF  ImageLayoutService total: 1.7464 sec.
[0407 13:02.27 @context.py:156]  INF  AnnotationNmsService total: 0.0009 sec.
[0407 13:02.27 @context.py:156]  INF  SubImageLayoutService total: 0.0 sec.
[0407 13:02.27 @context.py:156]  INF  PubtablesSegmentationService total: 0.0 sec.
[0407 13:02.27 @context.py:156]  INF  TextExtractionService total: 0.1212 sec.
[0407 13:02.27 @context.py:156]  INF  MatchingService total: 0.004 sec.
[0407 13:02.27 @context.py:156]  INF  TextOrderService total: 0.0086 sec.
[0407 13:02.27 @doctectionpipe.py:118]  INF  Processing Seq2RDF- An end-to-end application for deriving Triples from Natural Language Text_2.pdf
[0407 13:02.29 @context.py:156]  INF  ImageLayoutService total: 1.7282 sec.
[0407 13:02.29 @context.py:156]  INF  AnnotationNmsService total: 0.0009 sec.
[0407 13:02.30 @context.py:156]  INF  SubImageLayoutService total: 0.4494 sec.
[0407 13:02.30 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:02.30 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:02.30 @context.py:156]  INF  PubtablesSegmentationService total: 0.0037 sec.
[0407 13:02.30 @context.py:156]  INF  TextExtractionService total: 0.1694 sec.
[0407 13:02.30 @context.py:156]  INF  MatchingService total: 0.0073 sec.
[0407 13:02.30 @context.py:156]  INF  TextOrderService total: 0.0181 sec.
[0407 13:02.30 @doctectionpipe.py:118]  INF  Processing Seq2RDF- An end-to-end application for deriving Triples from Natural Language Text_3.pdf
[0407 13:02.32 @context.py:156]  INF  ImageLayoutService total: 1.8108 sec.
[0407 13:02.32 @context.py:156]  INF  AnnotationNmsService total: 0.0016 sec.
[0407 13:02.32 @context.py:156]  INF  SubImageLayoutService total: 0.2604 sec.
[0407 13:02.32 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:02.32 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:02.32 @context.py:156]  INF  PubtablesSegmentationService total: 0.0163 sec.
[0407 13:02.32 @context.py:156]  INF  TextExtractionService total: 0.1499 sec.
[0407 13:02.32 @context.py:156]  INF  MatchingService total: 0.0076 sec.
[0407 13:02.32 @context.py:156]  INF  TextOrderService total: 0.0249 sec.
[0407 13:02.32 @view.py:789]  WRN  html construction not possible
[0407 13:02.32 @view.py:789]  WRN  html construction not possible
[0407 13:02.32 @view.py:789]  WRN  html construction not possible
[0407 13:02.32 @view.py:789]  WRN  html construction not possible

Tablas detectadas: 2
  [table_1] página 2 → 1 filas × 2 cols
    Columnas: ['Text', 'Berlin is the capital city of Germany.']
  [table_2] página 3 → 5 filas × 4 cols
    Columnas: ['Tasks Metric', 'NYT F1-MeasureF1-Measure', 'ADE', 'Wiki-DBpedia F1-Measure']
  → Tablas incluidas en ground truth: 2

======================================================================
RESUMEN FINAL
======================================================================
  Adaptive Margin Ranking Loss for Knowledge Graph Embeddings  → 2 tablas
  Adversarial Contrastive Estimation                           → 4 tablas
  Binarized Knowledge Graph Embeddings                         → 5 tablas
  HyperKG- Hyperbolic Knowledge Graph Embeddings for Knowledge → 5 tablas
  Seq2RDF- An end-to-end application for deriving Triples from → 2 tablas

Total tablas extraídas: 18

## Compare table counts to manual ground truth

In [47]:
gt_manual_path = Path("pdfs_prueba/ground_truth/ground_truth_kge.json")

if gt_manual_path.exists():
    with open(gt_manual_path, 'r', encoding='utf-8') as f:
        gt_manual = json.load(f)
    manual_by_title = {d['paper_title']: d for d in gt_manual['documents']}

    print(f"{'Paper':<55} {'Manual':>8} {'DD':>6} {'Match':>6}")
    print('-' * 80)
    for doc in documents:
        title = doc['paper_title']
        dd_count = doc['num_tables']
        manual_doc = manual_by_title.get(title)
        manual_count = manual_doc['num_tables'] if manual_doc else '??'
        match = 'OK' if manual_doc and dd_count == manual_doc['num_tables'] else 'DIFF'
        print(f"{title[:55]:<55} {str(manual_count):>8} {dd_count:>6} {match:>6}")
else:
    print("Ground truth manual no encontrado.")

Paper                                                     Manual     DD  Match
--------------------------------------------------------------------------------
Adaptive Margin Ranking Loss for Knowledge Graph Embedd        2      2     OK
Adversarial Contrastive Estimation                             4      4     OK
Binarized Knowledge Graph Embeddings                           5      5     OK
HyperKG- Hyperbolic Knowledge Graph Embeddings for Know        4      5   DIFF
Seq2RDF- An end-to-end application for deriving Triples        2      2     OK

## Per-paper table preview

In [48]:
import pandas as pd

for doc in documents:
    print(f"\n{'='*70}")
    print(f"  {doc['paper_title']}")
    if not doc['tables']:
        print("  (sin tablas)")
        continue
    for t in doc['tables']:
        print(f"\n  [{t['table_id']}] página {t['page']} — "
              f"{t['evaluation']['expected_rows']} filas × {t['evaluation']['expected_cols']} cols")
        df_preview = pd.DataFrame(t['rows'], columns=t['evaluation']['columns'])
        display(df_preview.head(5))  # mostrar sólo las 5 primeras filas

======================================================================
  Adaptive Margin Ranking Loss for Knowledge Graph Embeddings via a Correntropy Objective Function

  [table_1] página 4 — 7 filas × 3 cols

            Data       FB15k        wn18
0      Optimizer     Adagrad     Adagrad
1  Embeddingsize         100         100
2       Epochs ξ  900000 0.1  900000 0.1
3              σ           1           1
4              λ           1           1

  [table_2] página 4 — 18 filas × 9 cols

,Dataset,WN18_Mean_raw,WN18_Mean_filter,WN18_Hits@10(%)_raw,WN18_Hits@10(%)_filter,FB15k_Mean_raw,FB15k_Mean_filter,FB15k_Hits@10(%)_raw,FB15k_Hits@10(%)_filter
0,Unstructured[6],315,304,35.5,38.2,1074,979,4.5,6.3
1,RESCALNickeletal.[22],1180,1163,37.2,52.8,828,683,28.4,44.1
2,SE[8],1011,985,68.5,80.5,273,162,28.8,39.8
3,SME(linear)[6],545,533,65.1,74.1,274,154,30.7,40.8
4,SME(bilinear)[6],526,509,54.7,61.3,284,158,31.3,41.3

======================================================================
  Adversarial Contrastive Estimation

  [table_1] página 7 — 9 filas × 3 cols

                                                         RW  WS353
0                            SkipgramOnlyNCEbaseline  18.90  31.35
1                                   Skipgram+OnlyADV  29.96  58.05
2                                       Skipgram+ACE  32.71  55.00
3  Glove-50(Recomputedbasedon(Penningtonetal.,2014))  34.02  49.51
4  Glove-100(Recomputedbasedon(Penningtonetal.,20...  36.64  52.76

  [table_2] página 7 — 4 filas × 6 cols

,,Queen,King,Computer,Man,Woman
0,Skip-GramNCETop5,princess king empress pxqueen monarch,prince queen kings emperor monarch,computers computing software microcomputer mai...,woman boy girl stranger person,girl man prostitute person divorcee
1,Skip-GramNCETop45-50,sambiria phongsri safrit mcelvoy tsarina,eraric mumbere empress saxonvm pretender,hypercard neurotechnology lgp pcs keystroke,angiomata someone bespectacled hero clown,suitor nymphomaniac barmaid redheaded jew
2,Skip-GramACETop5,princess prince elizabeth duke consort,prince vi kings duke iii,software computers applications computing hard...,woman girl tells dead boy,girl herself man lover tells
3,Skip-GramACETop45-50,baron abbey throne marie victoria,earl holy cardinal aragon princes,files information device design compatible,kid told revenge magic angry,aunt maid wife lady bride

  [table_3] página 7 — 2 filas × 2 cols

                    Method  Accuracy(%)
0         order-embeddings         90.6
1  order-embeddings+OurACE         92.0

  [table_4] página 8 — 8 filas × 3 cols

                                         MRR  hit@10
0                         ACE(Ent+SC)  0.792   0.945
1                      ACE(Ent+SC+IW)  0.768   0.949
2                     NCETransD(ours)  0.527   0.947
3           NCETransD((Jietal.,2015))      -   0.925
4  KBGAN(DISTMULT)((CaiandWang,2017))  0.772   0.948

======================================================================
  Binarized Knowledge Graph Embeddings

  [table_1] página 7 — 11 filas × 9 cols

,Models,WN18_MRR,WN18_Hits@_1,WN18_Hits@_3,WN18_Hits@_10,FB15k_MRR,FB15k_Hits@_1,FB15k_Hits@_3,FB15k_Hits@_10
0,TransE*,45.4,8.9,82.3,93.4,38.0,23.1,47.2,64.1
1,DistMult*,82.2,72.8,91.4,93.6,65.4,54.6,73.3,82.4
2,HolE*,93.8,93.0,94.5,94.9,52.4,40.2,61.3,73.9
3,ComplEx*,94.1,93.6,94.5,94.7,69.2,59.9,75.9,84.0
4,ANALOGY**,94.2,93.9,94.4,94.7,72.5,64.6,78.5,85.4

  [table_2] página 7 — 5 filas × 5 cols

                          WN18    FB15k  WN18RR  FB15k-237
0                  Ne   40.943   14.951  40.559     14.505
1                  Nr   18.000    1.345  11.000    237.000
2    #trainingtriples  141.442  483.142  86.835    272.115
3  #validationtriples    5.000   50.000   3.034     17.535
4        #testtriples    5.000   59.071   3.134     20.466

  [table_3] página 8 — 8 filas × 9 cols

,Models,WN18RR_MRR,WN18RR_Hits@_1,WN18RR_Hits@_3,WN18RR_Hits@_10,FB15k-237_MRR,FB15k-237_Hits@_1,FB15k-237_Hits@_3,FB15k-237_Hits@_10
0,DistMult*,43,39,44,49,24.1,15.5,26.3,41.9
1,ComplEx*,44,41,46,51,24.7,15.8,27.5,42.8
2,R-GCN*,-,-,-,-,24.8,15.3,25.8,41.7
3,ConvE*,43,40,44,52,32.5,23.7,35.6,50.1
4,CP(D=200),44,42,46,51,29.0,19.8,32.2,47.9

  [table_4] página 9 — 10 filas × 5 cols

,"Model_DistMult*(D=200) 6,400 ComplEx*(D=200) 12,800_ConvE*(D=200)_CP(D=15) CP(D=50)","Bitsperentity_DistMult*(D=200) 6,400 ComplEx*(D=200) 12,800_6,400_960_3,200","Bitsperrelation_6,400_12,800_6,400_480_1,600",MRR_WN18RR_43.0_44.0_43.0_40.0_43.0,MRR_FB15k-237_24.1_24.7_32.5_22.0_24.8
0,CP(D=200),12.8,6.4,44,29.0
1,CP(D=500),32.0,16.0,43,29.2
2,VQ-CP(D=200),400.0,200.0,36,8.7
3,VQ-CP(D=500),1.0,500.0,36,8.3
4,B-CP(D=100),200.0,100.0,38,23.2

  [table_5] página 11 — 3 filas × 3 cols

                Accuracy Modelsize
0     CP(D=15)      50.3     0.4GB
1    CP(D=200)      89.2     4.8GB
2  B-CP(D=400)      92.8     0.3GB

======================================================================
  HyperKG- Hyperbolic Knowledge Graph Embeddings for Knowledge Base Completion

  [table_1] página 5 — 4 filas × 6 cols

     Dataset      |E|  |R|   #Train  #Valid   #Test
0     WN18RR   40.943   11   86.835   3.034   3.134
1  FB15k-237   14.541  237  272.115  17.535  20.466
2         WD  418.000    2  550.000  25.000  25.000
3      WD ++  763.000    2    1.120  40.000  40.000

  [table_2] página 5 — 1 filas × 3 cols

   (a)   is a(x,y)∧part of(y,z)→part of(x,z)
0  (b)  part of(x,y)∧is  a(y,z)→part of(x,z)

  [table_3] página 6 — 6 filas × 6 cols

,Method,Type,WN18RR_MRR,WN18RR_H@10,FB15k-237_MRR,FB15k-237_H@10
0,DISTMULT(Yangetal.2015)[(cid:63)],Bilinear,0.43,49,0.24,41
1,ComplEx(Trouillonetal.2016)[(cid:63)],Bilinear,0.44,51,0.24,42
2,TransE(Bordesetal.2013)[(cid:63)],Translational,0.22,50,0.29,46
3,HyperKG(Mo¨biusaddition),Translational,0.30,44,0.19,32
4,HyperKG(noregularisation),Translational,0.30,46,0.25,41

  [table_4] página 6 — 2 filas × 5 cols

           Method        MRR WD H@10     WD MRR ++ H@10
0  ComplEx TransE  0.92 0.88   98 96  0.81 0.89   92 98
1         HyperKG       0.98      98       0.88      97

  [table_5] página 8 — 8 filas × 9 cols

,Dataset,Model,# negsE,# negsR,η,λ,n,"γ,",β
0,WN18RR,HyperKG,10,0,0.01,0.8,100,1.0,(cid:98)n(cid:99) 2
1,WN18RR,HyperKG(Mo¨biusaddition),10,0,0.01,-,100,1.0,(cid:98)n(cid:99) 2
2,WN18RR,HyperKG(noregularisation),10,0,0.01,0,100,1.0,(cid:98)n(cid:99) 2
3,FB15k-237,HyperKG,5,0,0.01,0.2,100,0.5,(cid:98)n(cid:99) 2
4,FB15k-237,HyperKG(Mo¨biusaddition),5,0,0.01,-,100,0.5,(cid:98)n(cid:99) 2

======================================================================
  Seq2RDF- An end-to-end application for deriving Triples from Natural Language Text

  [table_1] página 2 — 1 filas × 2 cols

     Text Berlin is the capital city of Germany.
0  Triple     dbr:Germany dbo:capital dbr:Berlin

  [table_2] página 3 — 5 filas × 4 cols

  Tasks Metric  NYT F1-MeasureF1-Measure   ADE  Wiki-DBpedia F1-Measure
0   EL+Lexical                      36.8  61.4                     37.8
1      EL+LSTM                      58.7  70.3                     65.5
2       EL+GRU                      59.8  73.2                     67.0
3      Seq2Seq                      64.2  73.4                     73.5
4      S+A+W+G                      71.4  79.5                     84.3

## Comparación detallada tabla a tabla

Para cada tabla, compara filas, columnas y estructura con el ground truth manual.  
Las diferencias marcadas con `DIFF` son candidatas a revisión manual.

In [49]:
if gt_manual_path.exists():
    for doc in documents:
        title = doc['paper_title']
        manual_doc = manual_by_title.get(title)
        if not manual_doc:
            print(f"\n[{title}] No encontrado en ground truth manual")
            continue

        print(f"\n{'='*70}")
        print(f"Paper: {title}")
        print(f"  Tablas manual: {manual_doc['num_tables']}  |  DD: {doc['num_tables']}")

        for i, dd_table in enumerate(doc['tables']):
            row_match = col_match = '?'
            m_rows = m_cols = '?'

            if i < len(manual_doc['tables']):
                m_table = manual_doc['tables'][i]
                m_rows = m_table['evaluation']['expected_rows']
                m_cols = m_table['evaluation']['expected_cols']
                row_match = 'OK' if dd_table['evaluation']['expected_rows'] == m_rows else 'DIFF'
                col_match = 'OK' if dd_table['evaluation']['expected_cols'] == m_cols else 'DIFF'

            print(f"\n  [{dd_table['table_id']}] página {dd_table['page']}")
            print(f"    DD     → {dd_table['evaluation']['expected_rows']} filas × {dd_table['evaluation']['expected_cols']} cols")
            print(f"    Manual → {m_rows} filas × {m_cols} cols")
            print(f"    Filas {row_match}  |  Columnas {col_match}")

            if col_match == 'DIFF':
                print(f"    Col DD:     {dd_table['evaluation']['columns']}")
                if i < len(manual_doc['tables']):
                    print(f"    Col Manual: {manual_doc['tables'][i]['evaluation']['columns']}")
else:
    print("Ground truth manual no disponible.")

======================================================================
Paper: Adaptive Margin Ranking Loss for Knowledge Graph Embeddings via a Correntropy Objective Function
  Tablas manual: 2  |  DD: 2

  [table_1] página 4
    DD     → 7 filas × 3 cols
    Manual → 19 filas × 9 cols
    Filas DIFF  |  Columnas DIFF
    Col DD:     ['Data', 'FB15k', 'wn18']
    Col Manual: ['Dataset', 'WN18_Mean_raw', 'WN18_Mean_filter', 'WN18_Hits@10_raw', 'WN18_Hits@10_filter', 'FB15k_Mean_raw', 'FB15k_Mean_filter', 'FB15k_Hits@10_raw', 'FB15k_Hits@10_filter']

  [table_2] página 4
    DD     → 18 filas × 9 cols
    Manual → 8 filas × 3 cols
    Filas DIFF  |  Columnas DIFF
    Col DD:     ['Dataset', 'WN18_Mean_raw', 'WN18_Mean_filter', 'WN18_Hits@10(%)_raw', 'WN18_Hits@10(%)_filter', 'FB15k_Mean_raw', 'FB15k_Mean_filter', 'FB15k_Hits@10(%)_raw', 'FB15k_Hits@10(%)_filter']
    Col Manual: ['Data', 'FB15k', 'wn18']

======================================================================
Paper: Adversarial Contrastive Estimation
  Tablas manual: 4  |  DD: 4

  [table_1] página 7
    DD     → 9 filas × 3 cols
    Manual → 20 filas × 6 cols
    Filas DIFF  |  Columnas DIFF
    Col DD:     ['', 'RW', 'WS353']
    Col Manual: ['Category', 'Queen', 'King', 'Computer', 'Man', 'Woman']

  [table_2] página 7
    DD     → 4 filas × 6 cols
    Manual → 9 filas × 3 cols
    Filas DIFF  |  Columnas DIFF
    Col DD:     ['', 'Queen', 'King', 'Computer', 'Man', 'Woman']
    Col Manual: ['Model', 'RW', 'WS353']

  [table_3] página 7
    DD     → 2 filas × 2 cols
    Manual → 2 filas × 2 cols
    Filas OK  |  Columnas OK

  [table_4] página 8
    DD     → 8 filas × 3 cols
    Manual → 8 filas × 3 cols
    Filas OK  |  Columnas OK

======================================================================
Paper: Binarized Knowledge Graph Embeddings
  Tablas manual: 5  |  DD: 5

  [table_1] página 7
    DD     → 11 filas × 9 cols
    Manual → 5 filas × 5 cols
    Filas DIFF  |  Columnas DIFF
    Col DD:     ['Models', 'WN18_MRR', 'WN18_Hits@_1', 'WN18_Hits@_3', 'WN18_Hits@_10', 'FB15k_MRR', 'FB15k_Hits@_1', 'FB15k_Hits@_3', 'FB15k_Hits@_10']
    Col Manual: ['', 'WN18', 'FB15k', 'WN18RR', 'FB15k-237']

  [table_2] página 7
    DD     → 5 filas × 5 cols
    Manual → 11 filas × 9 cols
    Filas DIFF  |  Columnas DIFF
    Col DD:     ['', 'WN18', 'FB15k', 'WN18RR', 'FB15k-237']
    Col Manual: ['Model', 'WN18_MRR', 'WN18_Hits@1', 'WN18_Hits@3', 'WN18_Hits@10', 'FB15k_MRR', 'FB15k_Hits@1', 'FB15k_Hits@3', 'FB15k_Hits@10']

  [table_3] página 8
    DD     → 8 filas × 9 cols
    Manual → 8 filas × 9 cols
    Filas OK  |  Columnas OK

  [table_4] página 9
    DD     → 10 filas × 5 cols
    Manual → 15 filas × 5 cols
    Filas DIFF  |  Columnas OK

  [table_5] página 11
    DD     → 3 filas × 3 cols
    Manual → 3 filas × 3 cols
    Filas OK  |  Columnas OK

======================================================================
Paper: HyperKG- Hyperbolic Knowledge Graph Embeddings for Knowledge Base Completion
  Tablas manual: 4  |  DD: 5

  [table_1] página 5
    DD     → 4 filas × 6 cols
    Manual → 4 filas × 6 cols
    Filas OK  |  Columnas OK

  [table_2] página 5
    DD     → 1 filas × 3 cols
    Manual → 6 filas × 6 cols
    Filas DIFF  |  Columnas DIFF
    Col DD:     ['(a)', 'is a(x,y)∧part', 'of(y,z)→part of(x,z)']
    Col Manual: ['Method', 'Type', 'WN18RR_MRR', 'WN18RR_H@10', 'FB15k-237_MRR', 'FB15k-237_H@10']

  [table_3] página 6
    DD     → 6 filas × 6 cols
    Manual → 3 filas × 5 cols
    Filas DIFF  |  Columnas DIFF
    Col DD:     ['Method', 'Type', 'WN18RR_MRR', 'WN18RR_H@10', 'FB15k-237_MRR', 'FB15k-237_H@10']
    Col Manual: ['Method', 'WD_MRR', 'WD_H@10', 'WD++_MRR', 'WD++_H@10']

  [table_4] página 6
    DD     → 2 filas × 5 cols
    Manual → 8 filas × 9 cols
    Filas DIFF  |  Columnas DIFF
    Col DD:     ['Method', 'MRR', 'WD H@10', 'WD MRR', '++ H@10']
    Col Manual: ['Dataset', 'Model', '#negs_E', '#negs_R', 'η', 'λ', 'n', 'γ', 'β']

  [table_5] página 8
    DD     → 8 filas × 9 cols
    Manual → ? filas × ? cols
    Filas ?  |  Columnas ?

======================================================================
Paper: Seq2RDF- An end-to-end application for deriving Triples from Natural Language Text
  Tablas manual: 2  |  DD: 2

  [table_1] página 2
    DD     → 1 filas × 2 cols
    Manual → 2 filas × 2 cols
    Filas DIFF  |  Columnas OK

  [table_2] página 3
    DD     → 5 filas × 4 cols
    Manual → 5 filas × 4 cols
    Filas OK  |  Columnas OK

## Guardar ground truth generado

Guarda el resultado en `ground_truth_deepdoctection.json` para revisión manual posterior.

In [50]:
OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

with open(OUTPUT_PATH, 'w', encoding='utf-8') as f:
    json.dump(ground_truth, f, indent=2, ensure_ascii=False)

print(f"Ground truth guardado en: {OUTPUT_PATH}")
print(f"Documentos:    {len(documents)}")
print(f"Total tablas:  {sum(d['num_tables'] for d in documents)}")

Ground truth guardado en: pdfs_prueba/ground_truth/ground_truth_deepdoctection.json
Documentos:    5
Total tablas:  18

# Generación de Ground Truth con DeepDoctection

Este notebook extrae tablas de los PDFs usando **deepdoctection** y genera un archivo JSON con el mismo formato del ground truth manual (`ground_truth_kge.json`).

El resultado será revisado y ajustado manualmente según las instrucciones en `ground_truth_manual.md`.

**Formato de salida:**
```json
{
  "documents": [
    {
      "paper_title": "...",
      "num_tables": N,
      "tables": [
        {
          "table_id": "table_1",
          "page": X,
          "evaluation": { "expected_rows": N, "expected_cols": M, "columns": [...] },
          "rows": [...]
        }
      ]
    }
  ]
}
```

In [51]:
import warnings
warnings.filterwarnings('ignore')

import json
import re
from pathlib import Path
from bs4 import BeautifulSoup
import deepdoctection as dd

## Configuración

In [52]:
# Directorio con los PDFs y ruta de salida
PDF_DIR = Path("pdfs_prueba")
OUTPUT_PATH = Path("pdfs_prueba/ground_truth/ground_truth_deepdoctection.json")

# Los 5 papers a procesar
PDF_FILES = sorted(PDF_DIR.glob("*.pdf"))
print(f"PDFs encontrados: {len(PDF_FILES)}")
for p in PDF_FILES:
    print(f"  - {p.name}")

PDFs encontrados: 5
  - Adaptive Margin Ranking Loss for Knowledge Graph Embeddings via a Correntropy Objective Function.pdf
  - Adversarial Contrastive Estimation.pdf
  - Binarized Knowledge Graph Embeddings.pdf
  - HyperKG- Hyperbolic Knowledge Graph Embeddings for Knowledge Base Completion.pdf
  - Seq2RDF- An end-to-end application for deriving Triples from Natural Language Text.pdf

## Funciones auxiliares

In [53]:
import re


def coerce_value(s: str):
    """
    Convierte un string a número si es posible; si es vacío/faltante, devuelve '-'.
    Maneja correctamente separadores de miles (ej. '40,943' → 40943, no 40.943).
    """
    s = s.strip()
    if not s or s in ('–', 'N/A', 'n/a', 'nan'):
        return '-'
    if s == '-':
        return '-'

    # Detectar si usa coma como separador de miles (ej. '40,943', '272,115')
    # vs. coma como separador decimal (ej. '0,83')
    # Heurística: si hay una coma seguida de exactamente 3 dígitos al final → miles
    s_clean = s
    if re.search(r',\d{3}(\D|$)', s):
        # Separador de miles: eliminar comas
        s_clean = s.replace(',', '')
    else:
        # Posible decimal europeo: sustituir coma por punto
        s_clean = s.replace(',', '.')

    try:
        val = float(s_clean)
        return int(val) if val == int(val) else val
    except ValueError:
        return s


def build_grid(rows_elements):
    """
    Construye una cuadrícula 2D resolviendo rowspan/colspan.
    Devuelve: grid dict {(row, col): text}, max_row, max_col, max_rowspan_reach,
              header_rows set (índices de filas que contienen <th>)
    """
    grid = {}
    max_rowspan_reach = 1
    th_rows = set()  # filas que contienen al menos un <th>

    for row_idx, row in enumerate(rows_elements):
        col_idx = 0
        for cell in row.find_all(['td', 'th']):
            while (row_idx, col_idx) in grid:
                col_idx += 1

            content = cell.get_text(separator=' ', strip=True)
            rowspan = int(cell.get('rowspan', 1))
            colspan = int(cell.get('colspan', 1))

            if cell.name == 'th':
                th_rows.add(row_idx)

            if rowspan > 1 or colspan > 1:
                max_rowspan_reach = max(max_rowspan_reach, row_idx + rowspan)

            for dr in range(rowspan):
                for dc in range(colspan):
                    grid[(row_idx + dr, col_idx + dc)] = content

            col_idx += colspan

    if not grid:
        return {}, 0, 0, 1, set()

    max_row = max(r for r, _ in grid.keys()) + 1
    max_col = max(c for _, c in grid.keys()) + 1
    return grid, max_row, max_col, max_rowspan_reach, th_rows


def detect_header_rows(th_rows, max_rowspan_reach, max_row):
    """
    Determina cuántas filas son de cabecera usando dos señales:
      1. Etiquetas <th> en el HTML (más fiable que contar spans).
      2. El alcance máximo de rowspan/colspan.
    Garantiza que siempre queda al menos 1 fila de datos.
    """
    if th_rows:
        # Tomar el rango continuo de filas <th> desde la fila 0
        max_th_row = max(th_rows)
        # Solo considerar filas <th> contiguas desde el inicio
        header_count = 0
        for i in range(max_th_row + 1):
            if i in th_rows or i <= max_th_row:
                header_count = i + 1
    else:
        # Fallback: usar alcance de spans
        header_count = max(1, max_rowspan_reach)

    # Nunca consumir todas las filas como cabecera
    return min(header_count, max_row - 1)


def flatten_headers(grid, header_row_count, max_col):
    """
    Aplana cabeceras multinivel para cada columna.
    - Elimina repeticiones consecutivas (causadas por rowspan propagation).
    - Corrige @_N → @N (underscore espurio antes de número tras @).
    Resultado: ['Models', 'WN18_MRR', 'WN18_Hits@1', 'WN18_Hits@10', ...]
    """
    columns = []
    for col_idx in range(max_col):
        parts = []
        prev = None
        for row_idx in range(header_row_count):
            val = grid.get((row_idx, col_idx), '').strip()
            if val and val != prev:
                parts.append(val)
            prev = val
        col_name = '_'.join(parts) if parts else ''
        # Corregir underscore espurio antes de número después de '@' → 'Hits@_10' → 'Hits@10'
        col_name = re.sub(r'@_(\d)', r'@\1', col_name)
        columns.append(col_name)
    return columns


def parse_table_html(html_str: str):
    """
    Parsea el HTML de una tabla de deepdoctection.
    - Detecta cabeceras usando etiquetas <th> (señal primaria) o spans (fallback).
    - Aplana encabezados multinivel y corrige artefactos tipográficos.
    - Convierte valores numéricos (manejo correcto de separadores de miles).

    Devuelve: (columns: list, data_rows: list[list]) o (None, None) si falla.
    """
    if not html_str:
        return None, None

    soup = BeautifulSoup(html_str, 'html.parser')
    table = soup.find('table')
    if not table:
        return None, None

    rows_elements = table.find_all('tr')
    if not rows_elements:
        return None, None

    grid, max_row, max_col, max_rowspan_reach, th_rows = build_grid(rows_elements)

    if not grid or max_col == 0 or max_row < 2:
        return None, None

    header_row_count = detect_header_rows(th_rows, max_rowspan_reach, max_row)

    columns = flatten_headers(grid, header_row_count, max_col)

    # Extraer filas de datos
    data_rows = []
    for row_idx in range(header_row_count, max_row):
        row = [coerce_value(grid.get((row_idx, c), '')) for c in range(max_col)]
        if all(v in ('-', '') for v in row):
            continue
        data_rows.append(row)

    return columns, data_rows


print("Funciones auxiliares cargadas.")

Funciones auxiliares cargadas.

## Inicializar DeepDoctection

Se usa **PDF Miner** (sin OCR) ya que los PDFs son texto nativo, lo que es más rápido y preciso.

In [54]:
analyzer = dd.get_dd_analyzer(config_overwrite=[
    'USE_PDF_MINER=True',
    'USE_OCR=False',
    'OCR.USE_DOCTR=False',
])
print("Analyzer listo:", type(analyzer).__name__)

[0407 13:02.33 @dd.py:119]  INF  Config:
 {'CELL': {'FILTER': None,
          'PAD': {'BOTTOM': 60, 'LEFT': 60, 'RIGHT': 60, 'TOP': 60},
          'PADDING': False,
          'WEIGHTS': 'cell/d2_model_1849999_cell_inf_only.pt',
          'WEIGHTS_TS': 'cell/d2_model_1849999_cell_inf_only.ts'},
 'DEVICE': device(type='mps'),
 'ENFORCE_WEIGHTS': {'CELL': True, 'ITEM': True, 'LAYOUT': True},
 'ITEM': {'FILTER': ['table'],
          'PAD': {'BOTTOM': 60, 'LEFT': 60, 'RIGHT': 60, 'TOP': 60},
          'PADDING': False,
          'WEIGHTS': 'deepdoctection/tatr_tab_struct_v2/model.safetensors',
          'WEIGHTS_TS': 'item/d2_model_1639999_item_inf_only.ts'},
 'LANGUAGE': None,
 'LAYOUT': {'FILTER': None,
            'PAD': {'BOTTOM': 0, 'LEFT': 0, 'RIGHT': 0, 'TOP': 0},
            'PADDING': False,
            'WEIGHTS': 'Aryn/deformable-detr-DocLayNet/model.safetensors',
            'WEIGHTS_TS': 'layout/d2_model_0829999_layout_inf_only.ts'},
 'LAYOUT_LINK': {'CHILD_CATEGORIES': [<LayoutType.CAPTION>],
                 'PARENTAL_CATEGORIES': [<LayoutType.FIGURE>, <LayoutType.TABLE>]},
 'LAYOUT_NMS_PAIRS': {'COMBINATIONS': [[<LayoutType.TABLE>, <LayoutType.TITLE>],
                                       [<LayoutType.TABLE>, <LayoutType.TEXT>],
                                       [<LayoutType.TABLE>, <LayoutType.KEY_VALUE_AREA>],
                                       [<LayoutType.TABLE>, <LayoutType.LIST_ITEM>],
                                       [<LayoutType.TABLE>, <LayoutType.LIST>],
                                       [<LayoutType.TABLE>, <LayoutType.FIGURE>],
                                       [<LayoutType.TITLE>, <LayoutType.TEXT>],
                                       [<LayoutType.TEXT>, <LayoutType.KEY_VALUE_AREA>],
                                       [<LayoutType.TEXT>, <LayoutType.LIST_ITEM>],
                                       [<LayoutType.TEXT>, <LayoutType.CAPTION>],
                                       [<LayoutType.KEY_VALUE_AREA>, <LayoutType.LIST_ITEM>],
                                       [<LayoutType.FIGURE>, <LayoutType.CAPTION>]],
                      'PRIORITY': [<LayoutType.TABLE>, <LayoutType.TABLE>, <LayoutType.TABLE>,
                                   <LayoutType.TABLE>, <LayoutType.TABLE>, <LayoutType.TABLE>,
                                   <LayoutType.TEXT>, <LayoutType.TEXT>, None, <LayoutType.CAPTION>,
                                   <LayoutType.KEY_VALUE_AREA>, <LayoutType.FIGURE>],
                      'THRESHOLDS': [0.001, 0.01, 0.01, 0.001, 0.01, 0.01, 0.05, 0.01, 0.01, 0.01,
                                     0.01, 0.001]},
 'LIB': 'PT',
 'LM_LANGUAGE_DETECT_CLASS': {'WEIGHTS': None},
 'LM_SEQUENCE_CLASS': {'USE_OTHER_AS_DEFAULT_CATEGORY': False, 'WEIGHTS': None},
 'LM_TOKEN_CLASS': {'SEGMENT_POSITIONS': None,
                    'SLIDING_WINDOW_STRIDE': 0,
                    'USE_OTHER_AS_DEFAULT_CATEGORY': False,
                    'WEIGHTS': None},
 'OCR': {'CONFIG': {'TESSERACT': 'dd/conf_tesseract.yaml'},
         'USE_DOCTR': False,
         'USE_TESSERACT': False,
         'USE_TEXTRACT': False,
         'WEIGHTS': {'DOCTR_RECOGNITION': 'doctr/crnn_vgg16_bn/crnn_vgg16_bn-0417f351.pt',
                     'DOCTR_WORD': 'doctr/db_resnet50/db_resnet50-ac60cadc.pt'}},
 'PDF_MINER': {'X_TOLERANCE': 3, 'Y_TOLERANCE': 3},
 'ROTATOR': {'MODEL': 'tesseract'},
 'SEGMENTATION': {'ASSIGNMENT_RULE': 'ioa',
                  'CELL_NAMES': [<CellType.COLUMN_HEADER>, <CellType.BODY>, <LayoutType.CELL>],
                  'FULL_TABLE_TILING': True,
                  'ITEM_NAMES': [<LayoutType.ROW>, <LayoutType.COLUMN>],
                  'PUBTABLES_CELL_NAMES': [<LayoutType.CELL>],
                  'PUBTABLES_ITEM_HEADER_CELL_NAMES': [<CellType.COLUMN_HEADER>,
                                                       <CellType.ROW_HEADER>,
                                                       <CellType.PROJECTED_ROW_HEADER>],
                  'PUBTABLES_ITEM_HEADER_THRESHOLDS': [0.6, 0.0001],
                  'PUBTABLES_ITEM_NAMES': [<LayoutType.ROW>, <LayoutType.COLUMN>],
                  'PUBTABLES_SPANNING_CELL_NAMES': [<CellType.SPANNING>],
                  'PUBTABLES_SUB_ITEM_NAMES': [<CellType.ROW_NUMBER>, <CellType.COLUMN_NUMBER>],
                  'REMOVE_IOU_THRESHOLD_COLS': 0.2,
                  'REMOVE_IOU_THRESHOLD_ROWS': 0.2,
                  'STRETCH_RULE': 'equal',
                  'SUB_ITEM_NAMES': [<CellType.ROW_NUMBER>, <CellType.COLUMN_NUMBER>],
                  'TABLE_NAME': <LayoutType.TABLE>,
                  'THRESHOLD_COLS': 0.4,
                  'THRESHOLD_ROWS': 0.4},
 'TEXT_CONTAINER': <LayoutType.WORD>,
 'TEXT_ORDERING': {'BROKEN_LINE_TOLERANCE': 0.003,
                   'FLOATING_TEXT_BLOCK_CATEGORIES': (<LayoutType.TEXT>, <LayoutType.TITLE>,
                                                      <LayoutType.LIST>,
                                                      <LayoutType.KEY_VALUE_AREA>),
                   'HEIGHT_TOLERANCE': 2.0,
                   'INCLUDE_RESIDUAL_TEXT_CONTAINER': True,
                   'PARAGRAPH_BREAK': 0.035,
                   'STARTING_POINT_TOLERANCE': 0.005,
                   'TEXT_BLOCK_CATEGORIES': (<LayoutType.TEXT>, <LayoutType.TITLE>,
                                             <LayoutType.LIST_ITEM>, <LayoutType.LIST>,
                                             <LayoutType.CAPTION>, <LayoutType.PAGE_HEADER>,
                                             <LayoutType.PAGE_FOOTER>, <LayoutType.PAGE_NUMBER>,
                                             <LayoutType.MARK>, <LayoutType.KEY_VALUE_AREA>,
                                             <LayoutType.FIGURE>, <CellType.SPANNING>,
                                             <LayoutType.CELL>)},
 'USE_LAYOUT': True,
 'USE_LAYOUT_LINK': False,
 'USE_LAYOUT_NMS': True,
 'USE_LINE_MATCHER': False,
 'USE_LM_LANGUAGE_DETECTION': False,
 'USE_LM_SEQUENCE_CLASS': False,
 'USE_LM_TOKEN_CLASS': False,
 'USE_OCR': False,
 'USE_PDF_MINER': True,
 'USE_ROTATOR': False,
 'USE_TABLE_REFINEMENT': False,
 'USE_TABLE_SEGMENTATION': True,
 'WORD_MATCHING': {'MAX_PARENT_ONLY': True,
                   'PARENTAL_CATEGORIES': (<LayoutType.TEXT>, <LayoutType.TITLE>,
                                           <LayoutType.LIST_ITEM>, <LayoutType.LIST>,
                                           <LayoutType.CAPTION>, <LayoutType.PAGE_HEADER>,
                                           <LayoutType.PAGE_FOOTER>, <LayoutType.PAGE_NUMBER>,
                                           <LayoutType.MARK>, <LayoutType.KEY_VALUE_AREA>,
                                           <LayoutType.FIGURE>, <CellType.SPANNING>,
                                           <LayoutType.CELL>),
                   'RULE': 'ioa',
                   'THRESHOLD': 0.3}}
You are using a model of type deformable_detr to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
[0407 13:02.33 @helpers.py:188]  INF  Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
You are using a model of type table-transformer to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
[0407 13:02.33 @helpers.py:188]  INF  Loading pretrained weights from url (https://download.pytorch.org/models/resnet18-5c106cde.pth)
[0407 13:02.34 @order.py:815]  WRN  In most cases floating_text_block_categories must be a subset of text_block_categories. Adding categories to floating_text_block_categories, that do not belong to text_block_categories makes only sense for categories set have CHILD relationships with annotations that belong to text_block_categories.

Analyzer listo: DoctectionPipe

## Extracción de tablas por paper

In [55]:
def extract_tables_from_pdf(pdf_path: Path, analyzer) -> dict:
    """
    Procesa un PDF con deepdoctection y devuelve una estructura de documento
    con el formato del ground truth.
    Nota: deepdoctection numera páginas desde 0; se suma +1 para coincidir
    con el GT manual (numeración 1-indexada).
    """
    paper_title = pdf_path.stem
    print(f"\n{'='*70}")
    print(f"Procesando: {paper_title}")
    print(f"{'='*70}")

    df = analyzer.analyze(path=str(pdf_path))
    df.reset_state()

    # Recolectar tablas de todas las páginas en orden de aparición
    all_tables_raw = []
    for page in df:
        # page.page_number es 0-indexed → +1 para numeración 1-indexada
        page_num_1based = page.page_number + 1
        for table in page.tables:
            all_tables_raw.append((page_num_1based, table))

    print(f"Tablas detectadas por deepdoctection: {len(all_tables_raw)}")

    tables_json = []
    table_counter = 0

    for page_num, table in all_tables_raw:
        html_str = table.html

        if not html_str:
            print(f"  [SKIP] tabla en página {page_num}: sin HTML")
            continue

        columns, data_rows = parse_table_html(html_str)

        if columns is None or not data_rows:
            print(f"  [SKIP] tabla en página {page_num}: no se pudo parsear o sin filas de datos")
            continue

        table_counter += 1
        table_id = f"table_{table_counter}"
        expected_rows = len(data_rows)
        expected_cols = len(columns)

        print(f"  [{table_id}] página {page_num} → {expected_rows} filas × {expected_cols} cols")
        print(f"    Columnas: {columns}")

        tables_json.append({
            "table_id": table_id,
            "page": page_num,
            "evaluation": {
                "expected_rows": expected_rows,
                "expected_cols": expected_cols,
                "columns": columns
            },
            "rows": data_rows
        })

    document = {
        "paper_title": paper_title,
        "num_tables": len(tables_json),
        "tables": tables_json
    }

    print(f"  → Tablas incluidas en ground truth: {len(tables_json)}")
    return document

## Ejecutar extracción en los 5 papers

In [56]:
documents = []

for pdf_path in PDF_FILES:
    doc = extract_tables_from_pdf(pdf_path, analyzer)
    documents.append(doc)

ground_truth = {"documents": documents}

print(f"\n{'='*70}")
print("RESUMEN FINAL")
print(f"{'='*70}")
total_tables = sum(d['num_tables'] for d in documents)
for d in documents:
    print(f"  {d['paper_title'][:60]:60s} → {d['num_tables']} tablas")
print(f"\nTotal tablas extraídas: {total_tables}")

======================================================================
Procesando: Adaptive Margin Ranking Loss for Knowledge Graph Embeddings via a Correntropy Objective Function
======================================================================

[0407 13:02.34 @doctectionpipe.py:118]  INF  Processing Adaptive Margin Ranking Loss for Knowledge Graph Embeddings via a Correntropy Objective Function_0.pdf
[0407 13:02.37 @context.py:156]  INF  ImageLayoutService total: 2.8548 sec.
[0407 13:02.37 @context.py:156]  INF  AnnotationNmsService total: 0.0018 sec.
[0407 13:02.37 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:02.37 @context.py:156]  INF  PubtablesSegmentationService total: 0.0002 sec.
[0407 13:02.37 @context.py:156]  INF  TextExtractionService total: 0.131 sec.
[0407 13:02.37 @context.py:156]  INF  MatchingService total: 0.0042 sec.
[0407 13:02.37 @context.py:156]  INF  TextOrderService total: 0.0093 sec.
[0407 13:02.37 @doctectionpipe.py:118]  INF  Processing Adaptive Margin Ranking Loss for Knowledge Graph Embeddings via a Correntropy Objective Function_1.pdf
[0407 13:02.39 @context.py:156]  INF  ImageLayoutService total: 1.8022 sec.
[0407 13:02.39 @context.py:156]  INF  AnnotationNmsService total: 0.0012 sec.
[0407 13:02.39 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:02.39 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:02.39 @context.py:156]  INF  TextExtractionService total: 0.1519 sec.
[0407 13:02.39 @context.py:156]  INF  MatchingService total: 0.0052 sec.
[0407 13:02.39 @context.py:156]  INF  TextOrderService total: 0.0155 sec.
[0407 13:02.39 @doctectionpipe.py:118]  INF  Processing Adaptive Margin Ranking Loss for Knowledge Graph Embeddings via a Correntropy Objective Function_2.pdf
[0407 13:02.41 @context.py:156]  INF  ImageLayoutService total: 1.7727 sec.
[0407 13:02.41 @context.py:156]  INF  AnnotationNmsService total: 0.002 sec.
[0407 13:02.41 @context.py:156]  INF  SubImageLayoutService total: 0.0002 sec.
[0407 13:02.41 @context.py:156]  INF  PubtablesSegmentationService total: 0.0002 sec.
[0407 13:02.41 @context.py:156]  INF  TextExtractionService total: 0.1581 sec.
[0407 13:02.41 @context.py:156]  INF  MatchingService total: 0.005 sec.
[0407 13:02.41 @context.py:156]  INF  TextOrderService total: 0.0226 sec.
[0407 13:02.41 @doctectionpipe.py:118]  INF  Processing Adaptive Margin Ranking Loss for Knowledge Graph Embeddings via a Correntropy Objective Function_3.pdf
[0407 13:02.43 @context.py:156]  INF  ImageLayoutService total: 1.8139 sec.
[0407 13:02.43 @context.py:156]  INF  AnnotationNmsService total: 0.0012 sec.
[0407 13:02.43 @context.py:156]  INF  SubImageLayoutService total: 0.0 sec.
[0407 13:02.43 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:02.43 @context.py:156]  INF  TextExtractionService total: 0.1058 sec.
[0407 13:02.43 @context.py:156]  INF  MatchingService total: 0.003 sec.
[0407 13:02.43 @context.py:156]  INF  TextOrderService total: 0.01 sec.
[0407 13:02.43 @doctectionpipe.py:118]  INF  Processing Adaptive Margin Ranking Loss for Knowledge Graph Embeddings via a Correntropy Objective Function_4.pdf
[0407 13:02.45 @context.py:156]  INF  ImageLayoutService total: 1.77 sec.
[0407 13:02.45 @context.py:156]  INF  AnnotationNmsService total: 0.0011 sec.
[0407 13:02.45 @context.py:156]  INF  SubImageLayoutService total: 0.418 sec.
[0407 13:02.45 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:02.45 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:02.45 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:02.45 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:02.46 @context.py:156]  INF  PubtablesSegmentationService total: 0.3511 sec.
[0407 13:02.46 @context.py:156]  INF  TextExtractionService total: 0.3056 sec.
[0407 13:02.46 @context.py:156]  INF  MatchingService total: 0.0115 sec.
[0407 13:02.46 @context.py:156]  INF  TextOrderService total: 0.1003 sec.
[0407 13:02.46 @doctectionpipe.py:118]  INF  Processing Adaptive Margin Ranking Loss for Knowledge Graph Embeddings via a Correntropy Objective Function_5.pdf
[0407 13:02.48 @context.py:156]  INF  ImageLayoutService total: 1.9189 sec.
[0407 13:02.48 @context.py:156]  INF  AnnotationNmsService total: 0.002 sec.
[0407 13:02.48 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:02.48 @context.py:156]  INF  PubtablesSegmentationService total: 0.0002 sec.
[0407 13:02.48 @context.py:156]  INF  TextExtractionService total: 0.4176 sec.
[0407 13:02.48 @context.py:156]  INF  MatchingService total: 0.0057 sec.
[0407 13:02.48 @context.py:156]  INF  TextOrderService total: 0.0227 sec.
[0407 13:02.48 @doctectionpipe.py:118]  INF  Processing Adaptive Margin Ranking Loss for Knowledge Graph Embeddings via a Correntropy Objective Function_6.pdf
[0407 13:02.50 @context.py:156]  INF  ImageLayoutService total: 1.803 sec.
[0407 13:02.50 @context.py:156]  INF  AnnotationNmsService total: 0.0016 sec.
[0407 13:02.50 @context.py:156]  INF  SubImageLayoutService total: 0.0 sec.
[0407 13:02.50 @context.py:156]  INF  PubtablesSegmentationService total: 0.0 sec.
[0407 13:02.50 @context.py:156]  INF  TextExtractionService total: 0.0064 sec.
[0407 13:02.50 @context.py:156]  INF  MatchingService total: 0.0005 sec.
[0407 13:02.50 @context.py:156]  INF  TextOrderService total: 0.0005 sec.
[0407 13:02.50 @view.py:789]  WRN  html construction not possible

Tablas detectadas por deepdoctection: 2
  [table_1] página 5 → 7 filas × 3 cols
    Columnas: ['Data', 'FB15k', 'wn18']

[0407 13:02.51 @doctectionpipe.py:118]  INF  Processing Adversarial Contrastive Estimation_0.pdf

  [table_2] página 5 → 18 filas × 9 cols
    Columnas: ['Dataset', 'WN18_Mean_raw', 'WN18_Mean_filter', 'WN18_Hits@10(%)_raw', 'WN18_Hits@10(%)_filter', 'FB15k_Mean_raw', 'FB15k_Mean_filter', 'FB15k_Hits@10(%)_raw', 'FB15k_Hits@10(%)_filter']
  → Tablas incluidas en ground truth: 2

======================================================================
Procesando: Adversarial Contrastive Estimation
======================================================================

[0407 13:02.53 @context.py:156]  INF  ImageLayoutService total: 2.0588 sec.
[0407 13:02.53 @context.py:156]  INF  AnnotationNmsService total: 0.0017 sec.
[0407 13:02.53 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:02.53 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:02.53 @context.py:156]  INF  TextExtractionService total: 0.2052 sec.
[0407 13:02.53 @context.py:156]  INF  MatchingService total: 0.0083 sec.
[0407 13:02.53 @context.py:156]  INF  TextOrderService total: 0.0214 sec.
[0407 13:02.53 @doctectionpipe.py:118]  INF  Processing Adversarial Contrastive Estimation_1.pdf
[0407 13:02.55 @context.py:156]  INF  ImageLayoutService total: 1.9876 sec.
[0407 13:02.55 @context.py:156]  INF  AnnotationNmsService total: 0.0017 sec.
[0407 13:02.55 @context.py:156]  INF  SubImageLayoutService total: 0.0 sec.
[0407 13:02.55 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:02.55 @context.py:156]  INF  TextExtractionService total: 0.3077 sec.
[0407 13:02.55 @context.py:156]  INF  MatchingService total: 0.0096 sec.
[0407 13:02.55 @context.py:156]  INF  TextOrderService total: 0.0288 sec.
[0407 13:02.55 @doctectionpipe.py:118]  INF  Processing Adversarial Contrastive Estimation_2.pdf
[0407 13:02.57 @context.py:156]  INF  ImageLayoutService total: 2.0191 sec.
[0407 13:02.57 @context.py:156]  INF  AnnotationNmsService total: 0.0012 sec.
[0407 13:02.57 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:02.57 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:02.58 @context.py:156]  INF  TextExtractionService total: 0.2841 sec.
[0407 13:02.58 @context.py:156]  INF  MatchingService total: 0.0092 sec.
[0407 13:02.58 @context.py:156]  INF  TextOrderService total: 0.029 sec.
[0407 13:02.58 @doctectionpipe.py:118]  INF  Processing Adversarial Contrastive Estimation_3.pdf
[0407 13:03.00 @context.py:156]  INF  ImageLayoutService total: 1.9531 sec.
[0407 13:03.00 @context.py:156]  INF  AnnotationNmsService total: 0.0013 sec.
[0407 13:03.00 @context.py:156]  INF  SubImageLayoutService total: 0.0 sec.
[0407 13:03.00 @context.py:156]  INF  PubtablesSegmentationService total: 0.0 sec.
[0407 13:03.00 @context.py:156]  INF  TextExtractionService total: 0.6089 sec.
[0407 13:03.00 @context.py:156]  INF  MatchingService total: 0.0109 sec.
[0407 13:03.00 @context.py:156]  INF  TextOrderService total: 0.0273 sec.
[0407 13:03.00 @doctectionpipe.py:118]  INF  Processing Adversarial Contrastive Estimation_4.pdf
[0407 13:03.03 @context.py:156]  INF  ImageLayoutService total: 2.2096 sec.
[0407 13:03.03 @context.py:156]  INF  AnnotationNmsService total: 0.0024 sec.
[0407 13:03.03 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:03.03 @context.py:156]  INF  PubtablesSegmentationService total: 0.0002 sec.
[0407 13:03.03 @context.py:156]  INF  TextExtractionService total: 0.3734 sec.
[0407 13:03.03 @context.py:156]  INF  MatchingService total: 0.0116 sec.
[0407 13:03.03 @context.py:156]  INF  TextOrderService total: 0.0412 sec.
[0407 13:03.03 @doctectionpipe.py:118]  INF  Processing Adversarial Contrastive Estimation_5.pdf
[0407 13:03.05 @context.py:156]  INF  ImageLayoutService total: 1.9794 sec.
[0407 13:03.05 @context.py:156]  INF  AnnotationNmsService total: 0.0011 sec.
[0407 13:03.05 @context.py:156]  INF  SubImageLayoutService total: 0.0 sec.
[0407 13:03.05 @context.py:156]  INF  PubtablesSegmentationService total: 0.0 sec.
[0407 13:03.05 @context.py:156]  INF  TextExtractionService total: 0.269 sec.
[0407 13:03.06 @context.py:156]  INF  MatchingService total: 0.009 sec.
[0407 13:03.06 @context.py:156]  INF  TextOrderService total: 0.0308 sec.
[0407 13:03.06 @doctectionpipe.py:118]  INF  Processing Adversarial Contrastive Estimation_6.pdf
[0407 13:03.08 @context.py:156]  INF  ImageLayoutService total: 2.0804 sec.
[0407 13:03.08 @context.py:156]  INF  AnnotationNmsService total: 0.0012 sec.
[0407 13:03.08 @context.py:156]  INF  SubImageLayoutService total: 0.0 sec.
[0407 13:03.08 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:03.08 @context.py:156]  INF  TextExtractionService total: 0.1986 sec.
[0407 13:03.08 @context.py:156]  INF  MatchingService total: 0.0077 sec.
[0407 13:03.08 @context.py:156]  INF  TextOrderService total: 0.0197 sec.
[0407 13:03.08 @doctectionpipe.py:118]  INF  Processing Adversarial Contrastive Estimation_7.pdf
[0407 13:03.10 @context.py:156]  INF  ImageLayoutService total: 2.0004 sec.
[0407 13:03.10 @context.py:156]  INF  AnnotationNmsService total: 0.0025 sec.
[0407 13:03.10 @context.py:156]  INF  SubImageLayoutService total: 0.4809 sec.
[0407 13:03.10 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:03.10 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:03.10 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:03.10 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:03.10 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:03.10 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:03.11 @context.py:156]  INF  PubtablesSegmentationService total: 0.0432 sec.
[0407 13:03.11 @context.py:156]  INF  TextExtractionService total: 0.438 sec.
[0407 13:03.11 @context.py:156]  INF  MatchingService total: 0.0077 sec.
[0407 13:03.11 @context.py:156]  INF  TextOrderService total: 0.0421 sec.
[0407 13:03.11 @doctectionpipe.py:118]  INF  Processing Adversarial Contrastive Estimation_8.pdf
[0407 13:03.13 @context.py:156]  INF  ImageLayoutService total: 2.1773 sec.
[0407 13:03.13 @context.py:156]  INF  AnnotationNmsService total: 0.0032 sec.
[0407 13:03.13 @context.py:156]  INF  SubImageLayoutService total: 0.184 sec.
[0407 13:03.13 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:03.13 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:03.13 @context.py:156]  INF  PubtablesSegmentationService total: 0.0131 sec.
[0407 13:03.14 @context.py:156]  INF  TextExtractionService total: 0.2668 sec.
[0407 13:03.14 @context.py:156]  INF  MatchingService total: 0.0092 sec.
[0407 13:03.14 @context.py:156]  INF  TextOrderService total: 0.0369 sec.
[0407 13:03.14 @doctectionpipe.py:118]  INF  Processing Adversarial Contrastive Estimation_9.pdf
[0407 13:03.16 @context.py:156]  INF  ImageLayoutService total: 2.0894 sec.
[0407 13:03.16 @context.py:156]  INF  AnnotationNmsService total: 0.002 sec.
[0407 13:03.16 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:03.16 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:03.16 @context.py:156]  INF  TextExtractionService total: 0.2448 sec.
[0407 13:03.16 @context.py:156]  INF  MatchingService total: 0.0095 sec.
[0407 13:03.16 @context.py:156]  INF  TextOrderService total: 0.0386 sec.
[0407 13:03.16 @doctectionpipe.py:118]  INF  Processing Adversarial Contrastive Estimation_10.pdf
[0407 13:03.18 @context.py:156]  INF  ImageLayoutService total: 1.9958 sec.
[0407 13:03.18 @context.py:156]  INF  AnnotationNmsService total: 0.0016 sec.
[0407 13:03.18 @context.py:156]  INF  SubImageLayoutService total: 0.0 sec.
[0407 13:03.18 @context.py:156]  INF  PubtablesSegmentationService total: 0.0002 sec.
[0407 13:03.18 @context.py:156]  INF  TextExtractionService total: 0.2577 sec.
[0407 13:03.18 @context.py:156]  INF  MatchingService total: 0.0101 sec.
[0407 13:03.19 @context.py:156]  INF  TextOrderService total: 0.043 sec.
[0407 13:03.19 @doctectionpipe.py:118]  INF  Processing Adversarial Contrastive Estimation_11.pdf
[0407 13:03.21 @context.py:156]  INF  ImageLayoutService total: 2.0298 sec.
[0407 13:03.21 @context.py:156]  INF  AnnotationNmsService total: 0.0022 sec.
[0407 13:03.21 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:03.21 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:03.21 @context.py:156]  INF  TextExtractionService total: 0.0368 sec.
[0407 13:03.21 @context.py:156]  INF  MatchingService total: 0.0034 sec.
[0407 13:03.21 @context.py:156]  INF  TextOrderService total: 0.004 sec.
[0407 13:03.21 @doctectionpipe.py:118]  INF  Processing Binarized Knowledge Graph Embeddings_0.pdf

Tablas detectadas por deepdoctection: 4
  [table_1] página 8 → 9 filas × 3 cols
    Columnas: ['', 'RW', 'WS353']
  [table_2] página 8 → 4 filas × 6 cols
    Columnas: ['', 'Queen', 'King', 'Computer', 'Man', 'Woman']
  [table_3] página 8 → 2 filas × 2 cols
    Columnas: ['Method', 'Accuracy(%)']
  [table_4] página 9 → 8 filas × 3 cols
    Columnas: ['', 'MRR', 'hit@10']
  → Tablas incluidas en ground truth: 4

======================================================================
Procesando: Binarized Knowledge Graph Embeddings
======================================================================

[0407 13:03.23 @context.py:156]  INF  ImageLayoutService total: 1.8653 sec.
[0407 13:03.23 @context.py:156]  INF  AnnotationNmsService total: 0.0009 sec.
[0407 13:03.23 @context.py:156]  INF  SubImageLayoutService total: 0.0 sec.
[0407 13:03.23 @context.py:156]  INF  PubtablesSegmentationService total: 0.0 sec.
[0407 13:03.23 @context.py:156]  INF  TextExtractionService total: 0.1375 sec.
[0407 13:03.23 @context.py:156]  INF  MatchingService total: 0.0058 sec.
[0407 13:03.23 @context.py:156]  INF  TextOrderService total: 0.0126 sec.
[0407 13:03.23 @doctectionpipe.py:118]  INF  Processing Binarized Knowledge Graph Embeddings_1.pdf
[0407 13:03.25 @context.py:156]  INF  ImageLayoutService total: 1.7621 sec.
[0407 13:03.25 @context.py:156]  INF  AnnotationNmsService total: 0.0008 sec.
[0407 13:03.25 @context.py:156]  INF  SubImageLayoutService total: 0.0 sec.
[0407 13:03.25 @context.py:156]  INF  PubtablesSegmentationService total: 0.0 sec.
[0407 13:03.25 @context.py:156]  INF  TextExtractionService total: 0.2306 sec.
[0407 13:03.25 @context.py:156]  INF  MatchingService total: 0.0085 sec.
[0407 13:03.25 @context.py:156]  INF  TextOrderService total: 0.0175 sec.
[0407 13:03.25 @doctectionpipe.py:118]  INF  Processing Binarized Knowledge Graph Embeddings_2.pdf
[0407 13:03.27 @context.py:156]  INF  ImageLayoutService total: 1.7675 sec.
[0407 13:03.27 @context.py:156]  INF  AnnotationNmsService total: 0.0009 sec.
[0407 13:03.27 @context.py:156]  INF  SubImageLayoutService total: 0.0 sec.
[0407 13:03.27 @context.py:156]  INF  PubtablesSegmentationService total: 0.0 sec.
[0407 13:03.27 @context.py:156]  INF  TextExtractionService total: 0.4465 sec.
[0407 13:03.27 @context.py:156]  INF  MatchingService total: 0.0074 sec.
[0407 13:03.27 @context.py:156]  INF  TextOrderService total: 0.0152 sec.
[0407 13:03.27 @doctectionpipe.py:118]  INF  Processing Binarized Knowledge Graph Embeddings_3.pdf
[0407 13:03.29 @context.py:156]  INF  ImageLayoutService total: 1.7695 sec.
[0407 13:03.29 @context.py:156]  INF  AnnotationNmsService total: 0.0011 sec.
[0407 13:03.29 @context.py:156]  INF  SubImageLayoutService total: 0.0 sec.
[0407 13:03.29 @context.py:156]  INF  PubtablesSegmentationService total: 0.0 sec.
[0407 13:03.29 @context.py:156]  INF  TextExtractionService total: 0.1827 sec.
[0407 13:03.29 @context.py:156]  INF  MatchingService total: 0.0076 sec.
[0407 13:03.29 @context.py:156]  INF  TextOrderService total: 0.0223 sec.
[0407 13:03.29 @doctectionpipe.py:118]  INF  Processing Binarized Knowledge Graph Embeddings_4.pdf
[0407 13:03.31 @context.py:156]  INF  ImageLayoutService total: 1.7537 sec.
[0407 13:03.31 @context.py:156]  INF  AnnotationNmsService total: 0.0009 sec.
[0407 13:03.31 @context.py:156]  INF  SubImageLayoutService total: 0.0 sec.
[0407 13:03.31 @context.py:156]  INF  PubtablesSegmentationService total: 0.0002 sec.
[0407 13:03.31 @context.py:156]  INF  TextExtractionService total: 0.1496 sec.
[0407 13:03.31 @context.py:156]  INF  MatchingService total: 0.0062 sec.
[0407 13:03.31 @context.py:156]  INF  TextOrderService total: 0.0195 sec.
[0407 13:03.31 @doctectionpipe.py:118]  INF  Processing Binarized Knowledge Graph Embeddings_5.pdf
[0407 13:03.33 @context.py:156]  INF  ImageLayoutService total: 1.7703 sec.
[0407 13:03.33 @context.py:156]  INF  AnnotationNmsService total: 0.0008 sec.
[0407 13:03.33 @context.py:156]  INF  SubImageLayoutService total: 0.0 sec.
[0407 13:03.33 @context.py:156]  INF  PubtablesSegmentationService total: 0.0 sec.
[0407 13:03.33 @context.py:156]  INF  TextExtractionService total: 0.168 sec.
[0407 13:03.33 @context.py:156]  INF  MatchingService total: 0.0154 sec.
[0407 13:03.33 @context.py:156]  INF  TextOrderService total: 0.0705 sec.
[0407 13:03.33 @doctectionpipe.py:118]  INF  Processing Binarized Knowledge Graph Embeddings_6.pdf
[0407 13:03.35 @context.py:156]  INF  ImageLayoutService total: 1.8115 sec.
[0407 13:03.35 @context.py:156]  INF  AnnotationNmsService total: 0.0009 sec.
[0407 13:03.35 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:03.35 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:03.35 @context.py:156]  INF  TextExtractionService total: 0.178 sec.
[0407 13:03.35 @context.py:156]  INF  MatchingService total: 0.0067 sec.
[0407 13:03.35 @context.py:156]  INF  TextOrderService total: 0.0339 sec.
[0407 13:03.35 @doctectionpipe.py:118]  INF  Processing Binarized Knowledge Graph Embeddings_7.pdf
[0407 13:03.37 @context.py:156]  INF  ImageLayoutService total: 1.7503 sec.
[0407 13:03.37 @context.py:156]  INF  AnnotationNmsService total: 0.0013 sec.
[0407 13:03.37 @context.py:156]  INF  SubImageLayoutService total: 0.2059 sec.
[0407 13:03.37 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:03.37 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:03.37 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:03.37 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:03.37 @context.py:156]  INF  PubtablesSegmentationService total: 0.1733 sec.
[0407 13:03.38 @context.py:156]  INF  TextExtractionService total: 0.2664 sec.
[0407 13:03.38 @context.py:156]  INF  MatchingService total: 0.0098 sec.
[0407 13:03.38 @context.py:156]  INF  TextOrderService total: 0.0896 sec.
[0407 13:03.38 @doctectionpipe.py:118]  INF  Processing Binarized Knowledge Graph Embeddings_8.pdf
[0407 13:03.40 @context.py:156]  INF  ImageLayoutService total: 1.7751 sec.
[0407 13:03.40 @context.py:156]  INF  AnnotationNmsService total: 0.0011 sec.
[0407 13:03.40 @context.py:156]  INF  SubImageLayoutService total: 0.095 sec.
[0407 13:03.40 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:03.40 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:03.40 @context.py:156]  INF  PubtablesSegmentationService total: 0.0844 sec.
[0407 13:03.40 @context.py:156]  INF  TextExtractionService total: 0.1934 sec.
[0407 13:03.40 @context.py:156]  INF  MatchingService total: 0.0087 sec.
[0407 13:03.40 @context.py:156]  INF  TextOrderService total: 0.0482 sec.
[0407 13:03.40 @doctectionpipe.py:118]  INF  Processing Binarized Knowledge Graph Embeddings_9.pdf
[0407 13:03.42 @context.py:156]  INF  ImageLayoutService total: 1.7695 sec.
[0407 13:03.42 @context.py:156]  INF  AnnotationNmsService total: 0.0009 sec.
[0407 13:03.42 @context.py:156]  INF  SubImageLayoutService total: 0.1013 sec.
[0407 13:03.42 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:03.42 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:03.42 @context.py:156]  INF  PubtablesSegmentationService total: 0.2818 sec.
[0407 13:03.42 @context.py:156]  INF  TextExtractionService total: 0.185 sec.
[0407 13:03.42 @context.py:156]  INF  MatchingService total: 0.0098 sec.
[0407 13:03.42 @context.py:156]  INF  TextOrderService total: 0.0464 sec.
[0407 13:03.42 @doctectionpipe.py:118]  INF  Processing Binarized Knowledge Graph Embeddings_10.pdf
[0407 13:03.44 @context.py:156]  INF  ImageLayoutService total: 1.7597 sec.
[0407 13:03.44 @context.py:156]  INF  AnnotationNmsService total: 0.0008 sec.
[0407 13:03.44 @context.py:156]  INF  SubImageLayoutService total: 0.0 sec.
[0407 13:03.44 @context.py:156]  INF  PubtablesSegmentationService total: 0.0 sec.
[0407 13:03.44 @context.py:156]  INF  TextExtractionService total: 0.1134 sec.
[0407 13:03.44 @context.py:156]  INF  MatchingService total: 0.0052 sec.
[0407 13:03.44 @context.py:156]  INF  TextOrderService total: 0.0089 sec.
[0407 13:03.44 @doctectionpipe.py:118]  INF  Processing Binarized Knowledge Graph Embeddings_11.pdf
[0407 13:03.46 @context.py:156]  INF  ImageLayoutService total: 1.7729 sec.
[0407 13:03.46 @context.py:156]  INF  AnnotationNmsService total: 0.0012 sec.
[0407 13:03.46 @context.py:156]  INF  SubImageLayoutService total: 0.1212 sec.
[0407 13:03.46 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:03.46 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:03.46 @context.py:156]  INF  PubtablesSegmentationService total: 0.0064 sec.
[0407 13:03.46 @context.py:156]  INF  TextExtractionService total: 0.1078 sec.
[0407 13:03.46 @context.py:156]  INF  MatchingService total: 0.0049 sec.
[0407 13:03.46 @context.py:156]  INF  TextOrderService total: 0.0144 sec.
[0407 13:03.46 @doctectionpipe.py:118]  INF  Processing Binarized Knowledge Graph Embeddings_12.pdf
[0407 13:03.48 @context.py:156]  INF  ImageLayoutService total: 1.7585 sec.
[0407 13:03.48 @context.py:156]  INF  AnnotationNmsService total: 0.0009 sec.
[0407 13:03.48 @context.py:156]  INF  SubImageLayoutService total: 0.0 sec.
[0407 13:03.48 @context.py:156]  INF  PubtablesSegmentationService total: 0.0 sec.
[0407 13:03.48 @context.py:156]  INF  TextExtractionService total: 0.1852 sec.
[0407 13:03.48 @context.py:156]  INF  MatchingService total: 0.0082 sec.
[0407 13:03.48 @context.py:156]  INF  TextOrderService total: 0.0213 sec.
[0407 13:03.48 @doctectionpipe.py:118]  INF  Processing Binarized Knowledge Graph Embeddings_13.pdf
[0407 13:03.50 @context.py:156]  INF  ImageLayoutService total: 1.7675 sec.
[0407 13:03.50 @context.py:156]  INF  AnnotationNmsService total: 0.0009 sec.
[0407 13:03.50 @context.py:156]  INF  SubImageLayoutService total: 0.0 sec.
[0407 13:03.50 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:03.50 @context.py:156]  INF  TextExtractionService total: 0.1841 sec.
[0407 13:03.50 @context.py:156]  INF  MatchingService total: 0.0075 sec.
[0407 13:03.50 @context.py:156]  INF  TextOrderService total: 0.0226 sec.
[0407 13:03.50 @doctectionpipe.py:118]  INF  Processing Binarized Knowledge Graph Embeddings_14.pdf
[0407 13:03.52 @context.py:156]  INF  ImageLayoutService total: 1.7538 sec.
[0407 13:03.52 @context.py:156]  INF  AnnotationNmsService total: 0.001 sec.
[0407 13:03.52 @context.py:156]  INF  SubImageLayoutService total: 0.0 sec.
[0407 13:03.52 @context.py:156]  INF  PubtablesSegmentationService total: 0.0 sec.
[0407 13:03.52 @context.py:156]  INF  TextExtractionService total: 0.0403 sec.
[0407 13:03.52 @context.py:156]  INF  MatchingService total: 0.0027 sec.
[0407 13:03.52 @context.py:156]  INF  TextOrderService total: 0.0042 sec.
[0407 13:03.52 @view.py:789]  WRN  html construction not possible
[0407 13:03.52 @view.py:789]  WRN  html construction not possible
[0407 13:03.52 @view.py:789]  WRN  html construction not possible
[0407 13:03.53 @view.py:789]  WRN  html construction not possible
[0407 13:03.53 @view.py:789]  WRN  html construction not possible
[0407 13:03.53 @view.py:789]  WRN  html construction not possible

Tablas detectadas por deepdoctection: 5
  [table_1] página 8 → 11 filas × 9 cols
    Columnas: ['Models', 'WN18_MRR', 'WN18_Hits@1', 'WN18_Hits@3', 'WN18_Hits@10', 'FB15k_MRR', 'FB15k_Hits@1', 'FB15k_Hits@3', 'FB15k_Hits@10']
  [table_2] página 8 → 5 filas × 5 cols
    Columnas: ['', 'WN18', 'FB15k', 'WN18RR', 'FB15k-237']
  [table_3] página 9 → 8 filas × 9 cols
    Columnas: ['Models', 'WN18RR_MRR', 'WN18RR_Hits@1', 'WN18RR_Hits@3', 'WN18RR_Hits@10', 'FB15k-237_MRR', 'FB15k-237_Hits@1', 'FB15k-237_Hits@3', 'FB15k-237_Hits@10']

[0407 13:03.53 @view.py:789]  WRN  html construction not possible
[0407 13:03.53 @view.py:789]  WRN  html construction not possible
[0407 13:03.53 @view.py:789]  WRN  html construction not possible
[0407 13:03.53 @view.py:789]  WRN  html construction not possible
[0407 13:03.53 @view.py:789]  WRN  html construction not possible
[0407 13:03.53 @doctectionpipe.py:118]  INF  Processing HyperKG- Hyperbolic Knowledge Graph Embeddings for Knowledge Base Completion_0.pdf

  [table_4] página 10 → 10 filas × 5 cols
    Columnas: ['Model_DistMult*(D=200) 6,400 ComplEx*(D=200) 12,800_ConvE*(D=200)_CP(D=15) CP(D=50)', 'Bitsperentity_DistMult*(D=200) 6,400 ComplEx*(D=200) 12,800_6,400_960_3,200', 'Bitsperrelation_6,400_12,800_6,400_480_1,600', 'MRR_WN18RR_43.0_44.0_43.0_40.0_43.0', 'MRR_FB15k-237_24.1_24.7_32.5_22.0_24.8']
  [table_5] página 12 → 3 filas × 3 cols
    Columnas: ['', 'Accuracy', 'Modelsize']
  → Tablas incluidas en ground truth: 5

======================================================================
Procesando: HyperKG- Hyperbolic Knowledge Graph Embeddings for Knowledge Base Completion
======================================================================

[0407 13:03.54 @context.py:156]  INF  ImageLayoutService total: 1.7734 sec.
[0407 13:03.54 @context.py:156]  INF  AnnotationNmsService total: 0.0015 sec.
[0407 13:03.54 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:03.54 @context.py:156]  INF  PubtablesSegmentationService total: 0.0003 sec.
[0407 13:03.55 @context.py:156]  INF  TextExtractionService total: 0.1259 sec.
[0407 13:03.55 @context.py:156]  INF  MatchingService total: 0.0054 sec.
[0407 13:03.55 @context.py:156]  INF  TextOrderService total: 0.0107 sec.
[0407 13:03.55 @doctectionpipe.py:118]  INF  Processing HyperKG- Hyperbolic Knowledge Graph Embeddings for Knowledge Base Completion_1.pdf
[0407 13:03.56 @context.py:156]  INF  ImageLayoutService total: 1.7606 sec.
[0407 13:03.56 @context.py:156]  INF  AnnotationNmsService total: 0.0013 sec.
[0407 13:03.56 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:03.56 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:03.57 @context.py:156]  INF  TextExtractionService total: 0.5372 sec.
[0407 13:03.57 @context.py:156]  INF  MatchingService total: 0.0092 sec.
[0407 13:03.57 @context.py:156]  INF  TextOrderService total: 0.0258 sec.
[0407 13:03.57 @doctectionpipe.py:118]  INF  Processing HyperKG- Hyperbolic Knowledge Graph Embeddings for Knowledge Base Completion_2.pdf
[0407 13:03.59 @context.py:156]  INF  ImageLayoutService total: 1.8292 sec.
[0407 13:03.59 @context.py:156]  INF  AnnotationNmsService total: 0.0011 sec.
[0407 13:03.59 @context.py:156]  INF  SubImageLayoutService total: 0.0 sec.
[0407 13:03.59 @context.py:156]  INF  PubtablesSegmentationService total: 0.0 sec.
[0407 13:03.59 @context.py:156]  INF  TextExtractionService total: 0.1721 sec.
[0407 13:03.59 @context.py:156]  INF  MatchingService total: 0.0057 sec.
[0407 13:03.59 @context.py:156]  INF  TextOrderService total: 0.0248 sec.
[0407 13:03.59 @doctectionpipe.py:118]  INF  Processing HyperKG- Hyperbolic Knowledge Graph Embeddings for Knowledge Base Completion_3.pdf
[0407 13:04.01 @context.py:156]  INF  ImageLayoutService total: 1.755 sec.
[0407 13:04.01 @context.py:156]  INF  AnnotationNmsService total: 0.0016 sec.
[0407 13:04.01 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:04.01 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:04.01 @context.py:156]  INF  TextExtractionService total: 0.2713 sec.
[0407 13:04.01 @context.py:156]  INF  MatchingService total: 0.0087 sec.
[0407 13:04.01 @context.py:156]  INF  TextOrderService total: 0.0397 sec.
[0407 13:04.01 @doctectionpipe.py:118]  INF  Processing HyperKG- Hyperbolic Knowledge Graph Embeddings for Knowledge Base Completion_4.pdf
[0407 13:04.03 @context.py:156]  INF  ImageLayoutService total: 1.8171 sec.
[0407 13:04.03 @context.py:156]  INF  AnnotationNmsService total: 0.0012 sec.
[0407 13:04.03 @context.py:156]  INF  SubImageLayoutService total: 0.0 sec.
[0407 13:04.03 @context.py:156]  INF  PubtablesSegmentationService total: 0.0 sec.
[0407 13:04.03 @context.py:156]  INF  TextExtractionService total: 0.2103 sec.
[0407 13:04.03 @context.py:156]  INF  MatchingService total: 0.0064 sec.
[0407 13:04.03 @context.py:156]  INF  TextOrderService total: 0.0143 sec.
[0407 13:04.03 @doctectionpipe.py:118]  INF  Processing HyperKG- Hyperbolic Knowledge Graph Embeddings for Knowledge Base Completion_5.pdf
[0407 13:04.05 @context.py:156]  INF  ImageLayoutService total: 1.7829 sec.
[0407 13:04.05 @context.py:156]  INF  AnnotationNmsService total: 0.0012 sec.
[0407 13:04.05 @context.py:156]  INF  SubImageLayoutService total: 0.2506 sec.
[0407 13:04.05 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:04.05 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:04.05 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:04.05 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:04.06 @context.py:156]  INF  PubtablesSegmentationService total: 0.0217 sec.
[0407 13:04.06 @context.py:156]  INF  TextExtractionService total: 0.2659 sec.
[0407 13:04.06 @context.py:156]  INF  MatchingService total: 0.0083 sec.
[0407 13:04.06 @context.py:156]  INF  TextOrderService total: 0.0359 sec.
[0407 13:04.06 @doctectionpipe.py:118]  INF  Processing HyperKG- Hyperbolic Knowledge Graph Embeddings for Knowledge Base Completion_6.pdf
[0407 13:04.08 @context.py:156]  INF  ImageLayoutService total: 1.8139 sec.
[0407 13:04.08 @context.py:156]  INF  AnnotationNmsService total: 0.0013 sec.
[0407 13:04.08 @context.py:156]  INF  SubImageLayoutService total: 0.1906 sec.
[0407 13:04.08 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:04.08 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:04.08 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:04.08 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:04.08 @context.py:156]  INF  PubtablesSegmentationService total: 0.043 sec.
[0407 13:04.08 @context.py:156]  INF  TextExtractionService total: 0.4665 sec.
[0407 13:04.08 @context.py:156]  INF  MatchingService total: 0.0082 sec.
[0407 13:04.08 @context.py:156]  INF  TextOrderService total: 0.0569 sec.
[0407 13:04.08 @doctectionpipe.py:118]  INF  Processing HyperKG- Hyperbolic Knowledge Graph Embeddings for Knowledge Base Completion_7.pdf
[0407 13:04.10 @context.py:156]  INF  ImageLayoutService total: 1.7923 sec.
[0407 13:04.10 @context.py:156]  INF  AnnotationNmsService total: 0.0012 sec.
[0407 13:04.10 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:04.10 @context.py:156]  INF  PubtablesSegmentationService total: 0.0001 sec.
[0407 13:04.11 @context.py:156]  INF  TextExtractionService total: 0.2845 sec.
[0407 13:04.11 @context.py:156]  INF  MatchingService total: 0.0081 sec.
[0407 13:04.11 @context.py:156]  INF  TextOrderService total: 0.103 sec.
[0407 13:04.11 @doctectionpipe.py:118]  INF  Processing HyperKG- Hyperbolic Knowledge Graph Embeddings for Knowledge Base Completion_8.pdf
[0407 13:04.12 @context.py:156]  INF  ImageLayoutService total: 1.7639 sec.
[0407 13:04.12 @context.py:156]  INF  AnnotationNmsService total: 0.0015 sec.
[0407 13:04.13 @context.py:156]  INF  SubImageLayoutService total: 0.0974 sec.
[0407 13:04.13 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:04.13 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:04.13 @context.py:156]  INF  PubtablesSegmentationService total: 0.0429 sec.
[0407 13:04.13 @context.py:156]  INF  TextExtractionService total: 0.2425 sec.
[0407 13:04.13 @context.py:156]  INF  MatchingService total: 0.0083 sec.
[0407 13:04.13 @context.py:156]  INF  TextOrderService total: 0.0647 sec.
[0407 13:04.13 @doctectionpipe.py:118]  INF  Processing HyperKG- Hyperbolic Knowledge Graph Embeddings for Knowledge Base Completion_9.pdf
[0407 13:04.15 @context.py:156]  INF  ImageLayoutService total: 1.7779 sec.
[0407 13:04.15 @context.py:156]  INF  AnnotationNmsService total: 0.0015 sec.
[0407 13:04.15 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:04.15 @context.py:156]  INF  PubtablesSegmentationService total: 0.0004 sec.
[0407 13:04.15 @context.py:156]  INF  TextExtractionService total: 0.1042 sec.
[0407 13:04.15 @context.py:156]  INF  MatchingService total: 0.0048 sec.
[0407 13:04.15 @context.py:156]  INF  TextOrderService total: 0.0149 sec.
[0407 13:04.15 @view.py:789]  WRN  html construction not possible
[0407 13:04.15 @view.py:789]  WRN  html construction not possible
[0407 13:04.15 @doctectionpipe.py:118]  INF  Processing Seq2RDF- An end-to-end application for deriving Triples from Natural Language Text_0.pdf

Tablas detectadas por deepdoctection: 5
  [table_1] página 6 → 4 filas × 6 cols
    Columnas: ['Dataset', '|E|', '|R|', '#Train', '#Valid', '#Test']
  [table_2] página 6 → 1 filas × 3 cols
    Columnas: ['(a)', 'is a(x,y)∧part', 'of(y,z)→part of(x,z)']
  [table_3] página 7 → 6 filas × 6 cols
    Columnas: ['Method', 'Type', 'WN18RR_MRR', 'WN18RR_H@10', 'FB15k-237_MRR', 'FB15k-237_H@10']
  [table_4] página 7 → 2 filas × 5 cols
    Columnas: ['Method', 'MRR', 'WD H@10', 'WD MRR', '++ H@10']
  [table_5] página 9 → 8 filas × 9 cols
    Columnas: ['Dataset', 'Model', '# negsE', '# negsR', 'η', 'λ', 'n', 'γ,', 'β']
  → Tablas incluidas en ground truth: 5

======================================================================
Procesando: Seq2RDF- An end-to-end application for deriving Triples from Natural Language Text
======================================================================

[0407 13:04.17 @context.py:156]  INF  ImageLayoutService total: 1.7654 sec.
[0407 13:04.17 @context.py:156]  INF  AnnotationNmsService total: 0.0012 sec.
[0407 13:04.17 @context.py:156]  INF  SubImageLayoutService total: 0.0001 sec.
[0407 13:04.17 @context.py:156]  INF  PubtablesSegmentationService total: 0.0 sec.
[0407 13:04.17 @context.py:156]  INF  TextExtractionService total: 0.1507 sec.
[0407 13:04.17 @context.py:156]  INF  MatchingService total: 0.0067 sec.
[0407 13:04.17 @context.py:156]  INF  TextOrderService total: 0.0155 sec.
[0407 13:04.17 @doctectionpipe.py:118]  INF  Processing Seq2RDF- An end-to-end application for deriving Triples from Natural Language Text_1.pdf
[0407 13:04.19 @context.py:156]  INF  ImageLayoutService total: 1.7611 sec.
[0407 13:04.19 @context.py:156]  INF  AnnotationNmsService total: 0.001 sec.
[0407 13:04.19 @context.py:156]  INF  SubImageLayoutService total: 0.0 sec.
[0407 13:04.19 @context.py:156]  INF  PubtablesSegmentationService total: 0.0006 sec.
[0407 13:04.19 @context.py:156]  INF  TextExtractionService total: 0.1225 sec.
[0407 13:04.19 @context.py:156]  INF  MatchingService total: 0.0039 sec.
[0407 13:04.19 @context.py:156]  INF  TextOrderService total: 0.0088 sec.
[0407 13:04.19 @doctectionpipe.py:118]  INF  Processing Seq2RDF- An end-to-end application for deriving Triples from Natural Language Text_2.pdf
[0407 13:04.21 @context.py:156]  INF  ImageLayoutService total: 1.7887 sec.
[0407 13:04.21 @context.py:156]  INF  AnnotationNmsService total: 0.0014 sec.
[0407 13:04.21 @context.py:156]  INF  SubImageLayoutService total: 0.1145 sec.
[0407 13:04.21 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:04.21 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:04.21 @context.py:156]  INF  PubtablesSegmentationService total: 0.0038 sec.
[0407 13:04.21 @context.py:156]  INF  TextExtractionService total: 0.1708 sec.
[0407 13:04.21 @context.py:156]  INF  MatchingService total: 0.0072 sec.
[0407 13:04.21 @context.py:156]  INF  TextOrderService total: 0.0184 sec.
[0407 13:04.21 @doctectionpipe.py:118]  INF  Processing Seq2RDF- An end-to-end application for deriving Triples from Natural Language Text_3.pdf
[0407 13:04.23 @context.py:156]  INF  ImageLayoutService total: 1.7892 sec.
[0407 13:04.23 @context.py:156]  INF  AnnotationNmsService total: 0.0012 sec.
[0407 13:04.23 @context.py:156]  INF  SubImageLayoutService total: 0.1131 sec.
[0407 13:04.23 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:04.23 @maputils.py:119]  WRN  MappingContextManager error. Will filter bounding box
[0407 13:04.23 @context.py:156]  INF  PubtablesSegmentationService total: 0.015 sec.
[0407 13:04.23 @context.py:156]  INF  TextExtractionService total: 0.1476 sec.
[0407 13:04.23 @context.py:156]  INF  MatchingService total: 0.0068 sec.
[0407 13:04.23 @context.py:156]  INF  TextOrderService total: 0.0248 sec.
[0407 13:04.23 @view.py:789]  WRN  html construction not possible
[0407 13:04.23 @view.py:789]  WRN  html construction not possible
[0407 13:04.23 @view.py:789]  WRN  html construction not possible
[0407 13:04.23 @view.py:789]  WRN  html construction not possible

Tablas detectadas por deepdoctection: 2
  [table_1] página 3 → 1 filas × 2 cols
    Columnas: ['Text', 'Berlin is the capital city of Germany.']
  [table_2] página 4 → 5 filas × 4 cols
    Columnas: ['Tasks Metric', 'NYT F1-MeasureF1-Measure', 'ADE', 'Wiki-DBpedia F1-Measure']
  → Tablas incluidas en ground truth: 2

======================================================================
RESUMEN FINAL
======================================================================
  Adaptive Margin Ranking Loss for Knowledge Graph Embeddings  → 2 tablas
  Adversarial Contrastive Estimation                           → 4 tablas
  Binarized Knowledge Graph Embeddings                         → 5 tablas
  HyperKG- Hyperbolic Knowledge Graph Embeddings for Knowledge → 5 tablas
  Seq2RDF- An end-to-end application for deriving Triples from → 2 tablas

Total tablas extraídas: 18

## Inspección rápida de resultados

Compara el número de tablas detectado por deepdoctection con el ground truth manual.

In [57]:
# Cargar ground truth manual para comparación
gt_manual_path = Path("pdfs_prueba/ground_truth/ground_truth_kge.json")
if gt_manual_path.exists():
    with open(gt_manual_path, 'r', encoding='utf-8') as f:
        gt_manual = json.load(f)

    manual_by_title = {d['paper_title']: d for d in gt_manual['documents']}

    print(f"{'Paper':<55} {'Manual':>8} {'DD':>8} {'Match':>8}")
    print('-' * 80)
    for doc in documents:
        title = doc['paper_title']
        dd_count = doc['num_tables']
        manual_doc = manual_by_title.get(title)
        manual_count = manual_doc['num_tables'] if manual_doc else '??'
        match = '✓' if manual_doc and dd_count == manual_doc['num_tables'] else '✗'
        print(f"{title[:55]:<55} {str(manual_count):>8} {dd_count:>8} {match:>8}")
else:
    print("Ground truth manual no encontrado, mostrando solo resultados DD:")
    for doc in documents:
        print(f"  {doc['paper_title']}: {doc['num_tables']} tablas")

Paper                                                     Manual       DD    Match
--------------------------------------------------------------------------------
Adaptive Margin Ranking Loss for Knowledge Graph Embedd        2        2        ✓
Adversarial Contrastive Estimation                             4        4        ✓
Binarized Knowledge Graph Embeddings                           5        5        ✓
HyperKG- Hyperbolic Knowledge Graph Embeddings for Know        4        5        ✗
Seq2RDF- An end-to-end application for deriving Triples        2        2        ✓

## Vista previa de una tabla extraída

Muestra la primera tabla del primer documento para verificar el formato.

In [58]:
import pandas as pd

for doc in documents:
    if doc['tables']:
        t = doc['tables'][0]
        print(f"Paper: {doc['paper_title']}")
        print(f"Tabla: {t['table_id']}  |  Página: {t['page']}")
        print(f"Columnas ({t['evaluation']['expected_cols']}): {t['evaluation']['columns']}")
        print()
        df = pd.DataFrame(t['rows'], columns=t['evaluation']['columns'])
        display(df)
        print()
        break

Paper: Adaptive Margin Ranking Loss for Knowledge Graph Embeddings via a Correntropy Objective Function
Tabla: table_1  |  Página: 5
Columnas (3): ['Data', 'FB15k', 'wn18']

            Data       FB15k        wn18
0      Optimizer     Adagrad     Adagrad
1  Embeddingsize         100         100
2       Epochs ξ  900000 0.1  900000 0.1
3              σ           1           1
4              λ           1           1
5              γ          30          15
6   Learningrate         0.1         0.1

## Guardar ground truth generado por deepdoctection

In [59]:
OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

with open(OUTPUT_PATH, 'w', encoding='utf-8') as f:
    json.dump(ground_truth, f, indent=2, ensure_ascii=False)

print(f"Ground truth guardado en: {OUTPUT_PATH}")
print(f"Documentos: {len(documents)}")
print(f"Total tablas: {sum(d['num_tables'] for d in documents)}")

Ground truth guardado en: pdfs_prueba/ground_truth/ground_truth_deepdoctection.json
Documentos: 5
Total tablas: 18

## Comparación detallada tabla a tabla (opcional)

Compara la estructura de cada tabla extraída con el ground truth manual.

In [60]:
if gt_manual_path.exists():
    for doc in documents:
        title = doc['paper_title']
        manual_doc = manual_by_title.get(title)
        if not manual_doc:
            print(f"\n[{title}] No encontrado en ground truth manual")
            continue

        print(f"\n{'='*70}")
        print(f"Paper: {title}")
        print(f"{'='*70}")
        print(f"  Tablas (manual): {manual_doc['num_tables']}  |  Tablas (DD): {doc['num_tables']}")

        for i, dd_table in enumerate(doc['tables']):
            print(f"\n  [{dd_table['table_id']}] página {dd_table['page']}")
            print(f"    DD     → {dd_table['evaluation']['expected_rows']} filas × {dd_table['evaluation']['expected_cols']} cols")

            if i < len(manual_doc['tables']):
                m_table = manual_doc['tables'][i]
                print(f"    Manual → {m_table['evaluation']['expected_rows']} filas × {m_table['evaluation']['expected_cols']} cols")
                row_match = dd_table['evaluation']['expected_rows'] == m_table['evaluation']['expected_rows']
                col_match = dd_table['evaluation']['expected_cols'] == m_table['evaluation']['expected_cols']
                print(f"    Filas {'✓' if row_match else '✗'}  |  Columnas {'✓' if col_match else '✗'}")
                if not col_match:
                    print(f"    Col DD:     {dd_table['evaluation']['columns']}")
                    print(f"    Col Manual: {m_table['evaluation']['columns']}")
else:
    print("Ground truth manual no disponible para comparación detallada.")

======================================================================
Paper: Adaptive Margin Ranking Loss for Knowledge Graph Embeddings via a Correntropy Objective Function
======================================================================
  Tablas (manual): 2  |  Tablas (DD): 2

  [table_1] página 5
    DD     → 7 filas × 3 cols
    Manual → 19 filas × 9 cols
    Filas ✗  |  Columnas ✗
    Col DD:     ['Data', 'FB15k', 'wn18']
    Col Manual: ['Dataset', 'WN18_Mean_raw', 'WN18_Mean_filter', 'WN18_Hits@10_raw', 'WN18_Hits@10_filter', 'FB15k_Mean_raw', 'FB15k_Mean_filter', 'FB15k_Hits@10_raw', 'FB15k_Hits@10_filter']

  [table_2] página 5
    DD     → 18 filas × 9 cols
    Manual → 8 filas × 3 cols
    Filas ✗  |  Columnas ✗
    Col DD:     ['Dataset', 'WN18_Mean_raw', 'WN18_Mean_filter', 'WN18_Hits@10(%)_raw', 'WN18_Hits@10(%)_filter', 'FB15k_Mean_raw', 'FB15k_Mean_filter', 'FB15k_Hits@10(%)_raw', 'FB15k_Hits@10(%)_filter']
    Col Manual: ['Data', 'FB15k', 'wn18']

======================================================================
Paper: Adversarial Contrastive Estimation
======================================================================
  Tablas (manual): 4  |  Tablas (DD): 4

  [table_1] página 8
    DD     → 9 filas × 3 cols
    Manual → 20 filas × 6 cols
    Filas ✗  |  Columnas ✗
    Col DD:     ['', 'RW', 'WS353']
    Col Manual: ['Category', 'Queen', 'King', 'Computer', 'Man', 'Woman']

  [table_2] página 8
    DD     → 4 filas × 6 cols
    Manual → 9 filas × 3 cols
    Filas ✗  |  Columnas ✗
    Col DD:     ['', 'Queen', 'King', 'Computer', 'Man', 'Woman']
    Col Manual: ['Model', 'RW', 'WS353']

  [table_3] página 8
    DD     → 2 filas × 2 cols
    Manual → 2 filas × 2 cols
    Filas ✓  |  Columnas ✓

  [table_4] página 9
    DD     → 8 filas × 3 cols
    Manual → 8 filas × 3 cols
    Filas ✓  |  Columnas ✓

======================================================================
Paper: Binarized Knowledge Graph Embeddings
======================================================================
  Tablas (manual): 5  |  Tablas (DD): 5

  [table_1] página 8
    DD     → 11 filas × 9 cols
    Manual → 5 filas × 5 cols
    Filas ✗  |  Columnas ✗
    Col DD:     ['Models', 'WN18_MRR', 'WN18_Hits@1', 'WN18_Hits@3', 'WN18_Hits@10', 'FB15k_MRR', 'FB15k_Hits@1', 'FB15k_Hits@3', 'FB15k_Hits@10']
    Col Manual: ['', 'WN18', 'FB15k', 'WN18RR', 'FB15k-237']

  [table_2] página 8
    DD     → 5 filas × 5 cols
    Manual → 11 filas × 9 cols
    Filas ✗  |  Columnas ✗
    Col DD:     ['', 'WN18', 'FB15k', 'WN18RR', 'FB15k-237']
    Col Manual: ['Model', 'WN18_MRR', 'WN18_Hits@1', 'WN18_Hits@3', 'WN18_Hits@10', 'FB15k_MRR', 'FB15k_Hits@1', 'FB15k_Hits@3', 'FB15k_Hits@10']

  [table_3] página 9
    DD     → 8 filas × 9 cols
    Manual → 8 filas × 9 cols
    Filas ✓  |  Columnas ✓

  [table_4] página 10
    DD     → 10 filas × 5 cols
    Manual → 15 filas × 5 cols
    Filas ✗  |  Columnas ✓

  [table_5] página 12
    DD     → 3 filas × 3 cols
    Manual → 3 filas × 3 cols
    Filas ✓  |  Columnas ✓

======================================================================
Paper: HyperKG- Hyperbolic Knowledge Graph Embeddings for Knowledge Base Completion
======================================================================
  Tablas (manual): 4  |  Tablas (DD): 5

  [table_1] página 6
    DD     → 4 filas × 6 cols
    Manual → 4 filas × 6 cols
    Filas ✓  |  Columnas ✓

  [table_2] página 6
    DD     → 1 filas × 3 cols
    Manual → 6 filas × 6 cols
    Filas ✗  |  Columnas ✗
    Col DD:     ['(a)', 'is a(x,y)∧part', 'of(y,z)→part of(x,z)']
    Col Manual: ['Method', 'Type', 'WN18RR_MRR', 'WN18RR_H@10', 'FB15k-237_MRR', 'FB15k-237_H@10']

  [table_3] página 7
    DD     → 6 filas × 6 cols
    Manual → 3 filas × 5 cols
    Filas ✗  |  Columnas ✗
    Col DD:     ['Method', 'Type', 'WN18RR_MRR', 'WN18RR_H@10', 'FB15k-237_MRR', 'FB15k-237_H@10']
    Col Manual: ['Method', 'WD_MRR', 'WD_H@10', 'WD++_MRR', 'WD++_H@10']

  [table_4] página 7
    DD     → 2 filas × 5 cols
    Manual → 8 filas × 9 cols
    Filas ✗  |  Columnas ✗
    Col DD:     ['Method', 'MRR', 'WD H@10', 'WD MRR', '++ H@10']
    Col Manual: ['Dataset', 'Model', '#negs_E', '#negs_R', 'η', 'λ', 'n', 'γ', 'β']

  [table_5] página 9
    DD     → 8 filas × 9 cols

======================================================================
Paper: Seq2RDF- An end-to-end application for deriving Triples from Natural Language Text
======================================================================
  Tablas (manual): 2  |  Tablas (DD): 2

  [table_1] página 3
    DD     → 1 filas × 2 cols
    Manual → 2 filas × 2 cols
    Filas ✗  |  Columnas ✓

  [table_2] página 4
    DD     → 5 filas × 4 cols
    Manual → 5 filas × 4 cols
    Filas ✓  |  Columnas ✓